export type Category = "Cleanse" | "Condition" | "Treat" | "Moisturize" | "Oils" | "Style";

export type Product = {
  slug: string;
  name: string;
  subtitle: string;
  category: Category;
  methodStep: number;
  benefit: string;
  description: string;
  directions: string;
  size: string | null;
  price: number | null;
  concerns: string[];
  styles: string[];
  ingredients: string[];
  featured?: boolean;
  variantId: string;
  stripeProductId: string | null;
  stripePriceId: string | null;
  images?: { src: string; alt: string }[];
};

// Catalog details are sourced from the matching product pages on wynnessentialsllc.us.
export const products: Product[] = [
  { slug: "hydrate-herbal-hair-mist", name: "Hydrate", subtitle: "Herbal Hair Mist", category: "Moisturize", methodStep: 4, benefit: "Revitalizing leave-in moisture for dry hair and scalp.", description: "Strengthen your hair and promote a healthy scalp with a revitalizing leave-in mist fortified with strengthening herbs. Hydrate leaves hair soft, smooth, and manageable while helping relieve dryness, flakiness, and itchiness.", directions: "Use daily or every other day. Lightly mist onto dry or damp hair, focusing on dry or tight areas, then gently smooth or scrunch. For best results, follow with Nourish Oil to seal in moisture.", size: "8 oz", price: 25.99, concerns: ["Dryness", "Protective Style Care"], styles: ["Braids", "Locs", "Twists", "Natural Curls", "Wigs and Weaves"], ingredients: ["Organic aloe vera leaf juice", "Purified water", "Behentrimonium methosulfate", "Emulsifying wax NF", "Vegetable glycerin", "Organic sunflower seed oil", "Organic jojoba seed oil", "Extra virgin olive oil", "Grapeseed oil", "Non-GMO soybean oil", "Vitamin E oil", "Cedarwood essential oil", "Chamomile extract", "Ginger root extract", "Stinging nettle extract", "Rosemary essential oil and extract", "Thyme extract", "Lemongrass essential oil", "Lavender essential oil", "Lecithin", "Peppermint essential oil", "Tea tree essential oil", "Saw palmetto extract", "Pumpkin seed oil", "Neem oil", "Panthenol", "Ethylhexylglycerin", "Phenoxyethanol"], featured: true, variantId: "default", stripeProductId: null, stripePriceId: null, images: [{ src: "/products/hydrate-official.png", alt: "Hydrate Mist official product photo" }, { src: "/products/hydrate-main.jpeg", alt: "Hydrate Herbal Hair Mist spray bottle" }, { src: "/collections/wynn-method-family.jpeg", alt: "Hydrate with selected Wynn Essentials routine products" }] },
  { slug: "thairap-moisture-styling-cream", name: "ThairaP", subtitle: "Moisture Styling Cream", category: "Style", methodStep: 6, benefit: "Softens, moisturizes, and defines without stiffness or weight.", description: "A rich yet lightweight styling cream for textured hair. Shea butter, castor oil, aloe vera, rice bran oil, and lavender help create touchable twist-outs, braid-outs, wash-and-gos, protective styles, and everyday moisture.", directions: "Apply a small amount to damp or dry hair. Work through strands from root to tip and style as desired. For best results, mist with Hydrate first.", size: "8 oz", price: 18.99, concerns: ["Dryness", "Definition and Styling"], styles: ["Twists", "Natural Curls", "Protective Styles"], ingredients: ["Aloe vera juice", "Stearic acid (palm derived)", "Behentrimonium methosulfate", "Cetearyl alcohol", "Shea butter", "Vegetable glycerin", "Castor seed oil", "Ethylhexylglycerin", "Phenoxyethanol", "Rice bran oil"], variantId: "default", stripeProductId: null, stripePriceId: null, images: [{ src: "/products/thairap-official-1.webp", alt: "Open ThairaP Moisture Styling Cream jar held against a bright orange background" }, { src: "/products/thairap-official-2.webp", alt: "Open ThairaP Moisture Styling Cream jar with labeled lid" }, { src: "/products/thairap-official-3.webp", alt: "Model holding four ThairaP jars beside lavender and aloe" }] },
  { slug: "lathyr-shampoo", name: "Lathyr", subtitle: "Gentle Cleansing Shampoo", category: "Cleanse", methodStep: 1, benefit: "Gently cleanses and resets the scalp without stripping moisture.", description: "A rich, botanical-infused, sulfate-free shampoo that cleanses while nourishing from root to tip. Organic oils and plant extracts help restore moisture balance, reduce breakage, and refresh the scalp.", directions: "Cleanse every 7–10 days. Saturate hair with lukewarm water, apply from roots to ends, and massage gently to avoid tangling. Rinse and repeat if needed, then follow with Uplyft Conditioner.", size: "8 oz", price: 19.99, concerns: ["Scalp Care"], styles: ["Braids", "Locs", "Twists", "Natural Curls", "Silk Press", "Wigs and Weaves"], ingredients: ["Aloe vera juice", "Cocamidopropyl betaine", "Decyl glucoside", "Sodium lauroyl lactylate", "Panthenol", "Polyquaternium-10", "Vegetable glycerin", "Ethylhexylglycerin", "Phenoxyethanol", "Rice bran oil", "Organic sunflower oil", "Organic hemp oil", "Organic jojoba oil", "Extra virgin olive oil", "Grapeseed oil", "Vitamin E oil", "Cedarwood essential oil", "Chamomile extract", "Ginger root extract", "Stinging nettle extract", "Rosemary essential oil and extract", "Thyme extract", "Lavender essential oil", "Lecithin", "Peppermint essential oil", "Tea tree essential oil", "Saw palmetto", "Pumpkin seed oil", "Neem oil"], variantId: "default", stripeProductId: null, stripePriceId: null, images: [{ src: "/products/lathyr-official.jpg", alt: "Lathyr official product photo" }, { src: "/products/lathyr-main.jpeg", alt: "Lathyr shampoo bottle" }, { src: "/collections/wynn-method-family.jpeg", alt: "Lathyr with selected Wynn Essentials routine products" }] },
  { slug: "uplyft-conditioner", name: "Uplyft", subtitle: "Deep Conditioner", category: "Condition", methodStep: 2, benefit: "Intense hydration, softness, strength, and shine for dry hair.", description: "A rich peach-and-honey deep conditioner made with aloe vera, honey, and nourishing oils. The formula melts into dry or damaged hair to restore softness without parabens, sulfates, or gluten.", directions: "Use every wash day or 1–2 times per week. Apply generously to clean, damp hair, cover with a plastic cap, and leave on for 20 minutes. For deeper penetration, use medium dryer heat, then rinse thoroughly.", size: "8 oz", price: 24.99, concerns: ["Dryness"], styles: ["Twists", "Natural Curls", "Silk Press", "Protective Styles"], ingredients: ["Organic aloe vera", "Behentrimonium methosulfate", "Cetearyl alcohol", "Stearic acid", "Panthenol", "Polyquaternium-10", "Vegetable glycerin", "Black castor oil", "Olive oil", "Sweet almond oil", "Honey", "Organic sunflower oil", "Ethylhexylglycerin", "Phenoxyethanol", "Rice bran oil", "Vitamin E", "Fragrance"], variantId: "default", stripeProductId: null, stripePriceId: null, images: [{ src: "/products/uplyft-official.jpg", alt: "Uplyft official product photo" }, { src: "/products/uplyft-main.png", alt: "Uplyft Moisture Rich Conditioner jar" }, { src: "/collections/wynn-method-family.jpeg", alt: "Uplyft with selected Wynn Essentials routine products" }] },
  { slug: "revaivl-protein-conditioner", name: "Revaivl", subtitle: "Protein-Rich Conditioner", category: "Treat", methodStep: 3, benefit: "Strengthens brittle, protein-depleted hair and supports elasticity.", description: "A protein-rich conditioner with aloe vera, rice protein, flax seed oil, rice bran oil, panthenol, and vitamin E. It helps rebuild, smooth, soften, and strengthen tired strands without heaviness.", directions: "Use 1–2 times per month. Apply to clean, damp hair, focusing on mid-lengths and ends. Detangle gently, cover for 10–15 minutes at room temperature without heat, rinse, and follow with a moisturizing leave-in.", size: "8 oz", price: 24.99, concerns: ["Weakness and Breakage"], styles: ["Twists", "Natural Curls", "Silk Press"], ingredients: ["Organic aloe vera leaf juice", "Behentrimonium methosulfate", "Cetearyl alcohol", "Emulsifying wax NF", "Rice protein", "Panthenol", "Polyquaternium-10", "Vegetable glycerin", "Flax seed oil", "Ethylhexylglycerin", "Phenoxyethanol", "Rice bran oil", "Vitamin E", "Fragrance"], variantId: "default", stripeProductId: null, stripePriceId: null, images: [{ src: "/products/revaivl-official.jpg", alt: "Revaivl official product photo" }, { src: "/products/revaivl-main.jpeg", alt: "Revaivl Protein Rich Conditioner jar" }] },
  { slug: "nourish-oil", name: "Nourish", subtitle: "Organic Oil Blend", category: "Oils", methodStep: 5, benefit: "Seals in moisture and revitalizes dry hair with botanical oils.", description: "An organic blend of sunflower oil, coconut oil, shea butter, and botanical extracts that nourishes and revitalizes hair, finished with the aromatic notes of cedarwood, lavender, and peppermint.", directions: "Apply 2–4 times per week to the scalp and/or ends. Shake well, warm a few drops between your palms, and apply gently. Best used after Hydrate or on damp hair to seal in moisture.", size: "2 oz", price: 21.99, concerns: ["Dryness"], styles: ["Braids", "Locs", "Twists", "Natural Curls"], ingredients: ["Sunflower oil", "Coconut oil", "Shea butter", "Rice bran oil", "Organic hemp seed oil", "Organic jojoba seed oil", "Olive oil", "Grapeseed oil", "Non-GMO soybean oil", "Vitamin E oil", "Cedarwood essential oil", "Chamomile extract", "Ginger root extract", "Stinging nettle extract", "Rosemary essential oil", "Thyme extract", "Lavender essential oil", "Lecithin", "Peppermint essential oil", "Tea tree essential oil", "Saw palmetto extract", "Pumpkin seed oil", "Neem oil"], variantId: "default", stripeProductId: null, stripePriceId: null, images: [{ src: "/products/nourish-official.png", alt: "Nourish Oil official product photo" }, { src: "/collections/wynn-method-family.jpeg", alt: "Nourish oil with selected Wynn Essentials routine products" }] },
  { slug: "grow-oil", name: "Grow", subtitle: "Organic Oil Blend", category: "Oils", methodStep: 5, benefit: "Nourishes the scalp and supports stronger, healthier-looking hair.", description: "An organic oil blend created to nourish the scalp, strengthen hair follicles, and support longer, thicker, healthier-looking hair while addressing thinning and breakage concerns.", directions: "Apply 2–3 times per week to a clean or refreshed scalp. Focus on thin, dry, or slow-growing areas and massage gently for 1–2 minutes. Do not rinse; style as usual.", size: "2 oz / 60 mL", price: 21.99, concerns: ["Scalp Care"], styles: ["Braids", "Locs", "Twists", "Wigs and Weaves"], ingredients: ["Black seed oil", "Safflower oil", "Jamaican black castor oil", "Coconut oil", "Avocado oil", "Lavender oil", "Rosemary oil", "Grapeseed oil", "Thyme oil", "Ylang ylang oil", "Vitamin E"], variantId: "default", stripeProductId: null, stripePriceId: null, images: [{ src: "/products/grow-official.png", alt: "Grow Oil official product photo" }, { src: "/products/grow-main.jpeg", alt: "Grow Organic Oil Blend dropper bottle" }] },
  { slug: "relief-oil", name: "Relief", subtitle: "Organic Scalp Oil", category: "Oils", methodStep: 5, benefit: "Soothes and moisturizes dry, itchy, dandruff-prone scalps.", description: "A targeted organic oil blend that deeply hydrates the scalp, relieves dryness and irritation, reduces itchiness, and helps combat dandruff—especially during protective styling or dry seasons.", directions: "Apply 1–3 times per week or as needed to dry, itchy, or irritated areas. Massage gently until absorbed. Do not rinse; avoid heavy application and part hair into sections for targeted use.", size: "2 oz", price: 23.99, concerns: ["Scalp Care", "Protective Style Care"], styles: ["Braids", "Locs", "Wigs and Weaves"], ingredients: ["Almond oil", "Jojoba oil", "Avocado oil", "Brazilian babassu oil", "Virgin black cumin seed oil", "Jamaican black castor oil", "Grapeseed oil", "Sunflower oil", "Tea tree oil", "Lemongrass oil", "Ylang ylang oil", "Rose oil"], variantId: "default", stripeProductId: null, stripePriceId: null, images: [
    { src: "/products/relief-official.png", alt: "Relief Organic Scalp Oil official product photo" },
    { src: "/editorial/relief-braids.jpeg", alt: "Relief Organic Scalp Oil for protective styles and braids" },
    { src: "/shoppable/relief-gift.jpeg", alt: "Relief Organic Scalp Oil presented in Wynn Essentials gift packaging" },
  ] },
  { slug: "edge-control", name: "Edge Control", subtitle: "Hydrating Styling Essential", category: "Style", methodStep: 6, benefit: "Smooths frizz and styles edges with castor and olive oils.", description: "A hydrating edge control formulated with castor oil, olive oil, aloe, and hydrolyzed silk to tame frizz, smooth the hairline, and support healthy-looking edges.", directions: "Use as needed, up to 2–4 times per week. Apply a small amount to clean, moisturized edges and gently smooth with a fingertip or soft edge brush. Avoid excessive brushing, tension, and daily buildup.", size: "4 oz", price: 14.99, concerns: ["Definition and Styling"], styles: ["Braids", "Locs", "Silk Press", "Wigs and Weaves"], ingredients: ["Water", "Ceteareth-25", "PEG-7 glyceryl cocoate", "Propylene glycol", "PEG-7 hydrogenated castor oil", "Aloe vera leaf juice", "Olive fruit oil", "Phenoxyethanol", "Fragrance", "Hydrolyzed silk", "Caprylyl glycol", "Ethylhexylglycerin", "Hexylene glycol"], variantId: "default", stripeProductId: null, stripePriceId: null, images: [{ src: "/products/edge-control-official.jpg", alt: "Edge Control official product photo" }, { src: "/products/edge-control-main.jpeg", alt: "Closed Wynn Essentials Edge Control jar" }, { src: "/products/edge-control-open.jpeg", alt: "Open Wynn Essentials Edge Control jar with labeled lid" }] },
];

export const method = [
  ["Cleanse", "Remove buildup without stripping natural moisture."],
  ["Condition", "Restore softness, slip, and manageability."],
  ["Treat", "Give weakened hair focused strength support."],
  ["Moisturize", "Replenish moisture lost through styling, weather, and time."],
  ["Seal", "Help retain moisture with intentional oils."],
  ["Style", "Create polished styles with moisture, hold, and definition."],
];

export const ingredientDescriptions: Record<string, string> = {
  Aloe: "A familiar botanical commonly used in formulas created for moisture and manageability.",
  Rosemary: "An aromatic botanical selected for thoughtful hair and scalp formulations.",
  Nettle: "A traditional botanical included in haircare formulations.",
  "Jojoba Oil": "A lightweight oil used to support softness and sealing.",
  "Sunflower Oil": "A plant oil selected for conditioning support.",
  Chamomile: "A familiar flower used in botanical haircare blends.",
  "Grapeseed Oil": "A light oil used in moisture-sealing routines.",
  "Vitamin E": "A formula component often paired with purposeful plant oils.",
  Lavender: "An aromatic botanical used in considered haircare blends.",
  Peppermint: "An aromatic ingredient used for its fresh sensory character.",
};

export const brandConfig = {
  announcement: "Free U.S. shipping on orders over $50.",
  shippingThreshold: 50,
  founder: { name: "The Wynn Sisters — Patricia, Sheree, and Karina Wynn", ownership: "Black women-owned", established: "Established 2020", location: "Los Angeles, California" },
  consent: "By joining, you agree to receive Wynn Essentials marketing messages. Consent is optional and can be withdrawn at any time. Message and data rates may apply.",
};
