import { BRAND, BUSINESS_ADDRESS, RESPONSIVE_STYLE, button, emailUrl, esc } from "./email-brand";
import { unsubscribeUrl } from "./unsubscribe";
import { annualMarketingCampaigns } from "./annual-marketing-campaigns";

export type AnnualMarketingCampaignId = typeof annualMarketingCampaigns[number]["id"];
const clean = (value: string) => value.replace(/<br\s*\/?\s*>/gi, "<br>");

export function annualMarketingEmail(id: AnnualMarketingCampaignId, email: string) {
  const campaign = annualMarketingCampaigns.find(item => item.id === id)!;
  const offer = campaign.offer ? `<tr><td style="padding:24px 32px;background:#fff8ed;text-align:center"><strong style="display:block;font:normal 30px ${BRAND.serif}">${esc(campaign.offer)}</strong>${campaign.terms ? `<span style="display:block;margin-top:8px;color:#6d6158;font:10px/17px ${BRAND.sans}">${esc(campaign.terms)}</span>` : ""}</td></tr>` : "";
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>${RESPONSIVE_STYLE}</style></head><body style="margin:0;background:#e8e1d8"><div style="display:none;max-height:0;overflow:hidden;opacity:0">${esc(campaign.preheader)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#e8e1d8"><tr><td align="center" style="padding:24px 10px"><table class="wrap" role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:600px;max-width:600px;background:#fff;border-collapse:collapse"><tr><td style="padding:24px;text-align:center"><img src="${emailUrl("/email/wynn-essentials-logo.png")}" width="230" alt="Wynn Essentials" style="display:block;width:230px;max-width:70%;height:auto;margin:auto"><p style="margin:7px 0 0;font:9px ${BRAND.sans};letter-spacing:.28em;text-transform:uppercase">${esc(campaign.tag)}</p></td></tr><tr><td><img class="fluid" src="${emailUrl(campaign.image)}" width="600" alt="${esc(campaign.imageAlt)}" style="display:block;width:100%;max-width:600px;height:auto;border:0"></td></tr><tr><td class="px" style="padding:42px 34px 46px;background:${campaign.background};color:${campaign.foreground};text-align:center"><p style="margin:0;color:${campaign.accent};font:900 10px ${BRAND.sans};letter-spacing:.2em;text-transform:uppercase">${esc(campaign.eyebrow)}</p><h1 class="h-lg" style="margin:13px 0 18px;font:normal 48px/.98 ${BRAND.serif};letter-spacing:-.04em;color:${campaign.foreground}">${clean(campaign.title)}</h1><p style="max-width:475px;margin:0 auto 24px;font:14px/24px ${BRAND.sans}">${esc(campaign.body)}</p>${button(campaign.cta, emailUrl(campaign.href), "center", BRAND.pink, BRAND.white)}</td></tr>${offer}<tr><td style="padding:28px 34px;background:#f4eee6;text-align:center;color:#675d54;font:10px/18px ${BRAND.sans}">WYNN ESSENTIALS · Healthy Hair Is a Practice<br>${BUSINESS_ADDRESS}<br><a href="${emailUrl("/")}" style="color:#675d54">Shop</a> · <a href="${unsubscribeUrl(email)}" style="color:#675d54">Unsubscribe</a></td></tr></table></td></tr></table></body></html>`;
  return { subject: campaign.subject, html, text: `${campaign.subject}\n\n${campaign.body}\n\n${campaign.cta}: ${emailUrl(campaign.href)}\nUnsubscribe: ${unsubscribeUrl(email)}` };
}
