export const annualMarketingCampaigns = [
  {
    "id": "thanks-2026",
    "name": "Healthy Hair Is a Practice",
    "subject": "A grateful note from Wynn Essentials",
    "preheader": "Today, we’re celebrating the people behind every healthy-hair practice.",
    "scheduledAt": new Date("2026-11-26T17:00:00Z"),
    "expiresAt": new Date("2026-11-27T17:00:00Z"),
    "tag": "Healthy Hair Is a Practice",
    "image": "/founders-patricia-karina-sheree.png",
    "imageAlt": "The women behind Wynn Essentials",
    "eyebrow": "A Thanksgiving Note",
    "title": "Grateful for every crown<br>you’ve trusted us to care for.",
    "body": "Wynn Essentials began with a belief that healthy hair is built through care, consistency and community. Every order, review, recommendation and wash-day ritual has helped this practice grow. Today, we simply want to say thank you for letting us be part of yours.",
    "cta": "Visit Wynn Essentials",
    "href": "/",
    "background": "#6b4634",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "early-2026",
    "name": "Private Holiday Access",
    "subject": "You’re invited: Black Friday starts now",
    "preheader": "Early access to 25% off Wynn Essentials haircare and styling.",
    "scheduledAt": new Date("2026-11-27T02:00:00Z"),
    "expiresAt": new Date("2026-11-28T02:00:00Z"),
    "tag": "Private Holiday Access",
    "image": "/collections/wynn-essentials-gold-editorial.webp",
    "imageAlt": "Wynn Essentials gold holiday editorial",
    "eyebrow": "Subscriber Early Access",
    "title": "Your practice deserves<br>the first invitation.",
    "body": "Before the doors open to everyone, replenish the products that keep your routine consistent—or begin the ritual your hair has been asking for.",
    "cta": "Unlock 25% Off",
    "href": "/",
    "background": "#1f3b32",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "BLACKFRIDAY25",
    "terms": "Excludes Boho Hair preorders, gift cards and previously discounted items. Offers cannot be combined."
  },
  {
    "id": "blackfriday-2026",
    "name": "The Practice Starts Here",
    "subject": "Black Friday: 25% off your healthy-hair practice",
    "preheader": "Your wash day, moisture and styling essentials are waiting.",
    "scheduledAt": new Date("2026-11-27T15:00:00Z"),
    "expiresAt": new Date("2026-11-28T15:00:00Z"),
    "tag": "The Practice Starts Here",
    "image": "/collections/wynn-essentials-oils-giftbox.webp",
    "imageAlt": "Wynn Essentials hair oils and Edge Control presented in a gift box",
    "eyebrow": "The Main Event",
    "title": "Invest in the ritual.<br>Save on the essentials.",
    "body": "Cleanse without stripping. Condition with intention. Restore moisture, support the scalp and finish every style with care. Today, build the complete practice for 25% less.",
    "cta": "Shop Black Friday",
    "href": "/",
    "background": "#251b17",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "BLACKFRIDAY25",
    "terms": "Valid November 27, 2026. Excludes Boho Hair preorders, gift cards and previously discounted items. Cannot be combined."
  },
  {
    "id": "small-2026",
    "name": "Small Business Saturday",
    "subject": "Shop small today, receive $25 for tomorrow",
    "preheader": "Spend $100 and receive a $25 Wynn Essentials January credit.",
    "scheduledAt": new Date("2026-11-28T16:00:00Z"),
    "expiresAt": new Date("2026-11-29T16:00:00Z"),
    "tag": "Small Business Saturday",
    "image": "/collections/wynn-essentials-three-hands.webp",
    "imageAlt": "Three hands presenting Wynn Essentials Grow, Nourish and Relief oils",
    "eyebrow": "A Thank-You for Supporting Small",
    "title": "Spend $100 today.<br>Receive $25 for January.",
    "body": "Care for your holiday routine now, then return in the new year with a $25 Wynn Essentials credit toward your next practice.",
    "cta": "Support & Shop Small",
    "href": "/",
    "background": "#8b3d52",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": "Qualifying merchandise subtotal must reach $100 after discounts and before shipping and tax. Credit is issued by email and valid during January 2027 with a minimum purchase. Final terms to be confirmed before scheduling."
  },
  {
    "id": "cyber-2026",
    "name": "Delivered to Your Door",
    "subject": "Cyber Monday: 20% off + free shipping",
    "preheader": "One online-only day to complete your Wynn Essentials ritual.",
    "scheduledAt": new Date("2026-11-30T15:00:00Z"),
    "expiresAt": new Date("2026-12-01T15:00:00Z"),
    "tag": "Delivered to Your Door",
    "image": "/collections/wynn-essentials-brand-bag.webp",
    "imageAlt": "Wynn Essentials branded shopping bag and products",
    "eyebrow": "Your Cart Called",
    "title": "Complete the practice<br>from cleanse to finish.",
    "body": "For one day only, take 20% off eligible haircare and styling essentials—and we’ll cover standard U.S. shipping.",
    "cta": "Shop Cyber Monday",
    "href": "/",
    "background": "#3b274d",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "CYBER20",
    "terms": "Valid November 30, 2026 through 11:59 PM PT. Excludes Boho Hair preorders, gift cards and previously discounted items. Cannot be combined."
  },
  {
    "id": "final-2026",
    "name": "Last Call for the Ritual",
    "subject": "Final hours: 20% off + free shipping ends tonight",
    "preheader": "Your Cyber Monday offer disappears at 11:59 PM PT.",
    "scheduledAt": new Date("2026-12-01T02:00:00Z"),
    "expiresAt": new Date("2026-12-02T02:00:00Z"),
    "tag": "Last Call for the Ritual",
    "image": "/newsletter/newsletter-campaign-posters.webp",
    "imageAlt": "Wynn Essentials campaign imagery",
    "eyebrow": "Ends at 11:59 PM PT",
    "title": "Before the clock runs out,<br>choose what your hair needs.",
    "body": "There are only a few hours left to receive 20% off eligible haircare and styling products plus free standard U.S. shipping.",
    "cta": "Use Code CYBER20",
    "href": "/",
    "background": "#1d1815",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": "Valid November 30, 2026 through 11:59 PM PT. Excludes Boho Hair preorders, gift cards and previously discounted items. Cannot be combined."
  },
  {
    "id": "guide-2026",
    "name": "The Holiday Gift Guide",
    "subject": "The Wynn Essentials Holiday Gift Guide",
    "preheader": "Thoughtful hair wellness gifts for every practice.",
    "scheduledAt": new Date("2026-12-04T17:00:00Z"),
    "expiresAt": new Date("2026-12-05T17:00:00Z"),
    "tag": "The Holiday Gift Guide",
    "image": "/newsletter/newsletter-bubblegum-pigtails.webp",
    "imageAlt": "Woman wearing polished textured pigtails with bronze satin scrunchies",
    "eyebrow": "Give the Gift of the Practice",
    "title": "Beautiful rituals.<br>Thoughtfully chosen.",
    "body": "For the wash-day devotee, the protective-style lover and the person ready to care for their crown with more intention—there is a Wynn Essentials gift for them.",
    "cta": "Explore the Gift Guide",
    "href": "/",
    "background": "#4e1b25",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "gifting-2026",
    "name": "Wrapped in Intention",
    "subject": "The art of gifting—15% off curated bundles",
    "preheader": "Give a complete healthy-hair ritual, beautifully considered.",
    "scheduledAt": new Date("2026-12-10T16:00:00Z"),
    "expiresAt": new Date("2026-12-11T16:00:00Z"),
    "tag": "Wrapped in Intention",
    "image": "/collections/wynn-essentials-linen-bag.webp",
    "imageAlt": "Wynn Essentials linen gift bag presented in a holiday box",
    "eyebrow": "The Art of Gifting",
    "title": "Give more than a product.<br>Give them a practice.",
    "body": "Our curated bundles pair essentials that work beautifully together—making thoughtful gifting feel effortless.",
    "cta": "Shop Curated Bundles",
    "href": "/",
    "background": "#17362e",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "GIFT15",
    "terms": "Excludes Boho Hair preorders, gift cards and previously discounted merchandise. Cannot be combined. Final eligible bundles to be confirmed."
  },
  {
    "id": "shipping-2026",
    "name": "Your Holiday Shipping Reminder",
    "subject": "Order by December 14 for expected Christmas delivery",
    "preheader": "Place your holiday order today and let us prepare it with care.",
    "scheduledAt": new Date("2026-12-14T16:00:00Z"),
    "expiresAt": new Date("2026-12-15T16:00:00Z"),
    "tag": "Your Holiday Shipping Reminder",
    "image": "/newsletter/newsletter-hydrate-afro-purple.webp",
    "imageAlt": "Woman refreshing her natural hair with Wynn Essentials Hydrate",
    "eyebrow": "A Gentle Holiday Reminder",
    "title": "Give your gifts time<br>to arrive beautifully.",
    "body": "Order eligible in-stock products by December 14 for expected delivery before Christmas. Every Wynn Essentials order is prepared with care—and a little extra time helps it reach you without the rush.",
    "cta": "Complete Your Gift List",
    "href": "/",
    "background": "#9a422c",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": "Recommended date requires final confirmation before scheduling. Delivery dates are estimates, not guarantees. Boho Hair preorders are excluded from Christmas-arrival messaging."
  },
  {
    "id": "lastminute-2026",
    "name": "A Ritual for You",
    "subject": "A little holiday care—for you",
    "preheader": "Free shipping, no minimum, on your last-minute self-care order.",
    "scheduledAt": new Date("2026-12-19T17:00:00Z"),
    "expiresAt": new Date("2026-12-20T17:00:00Z"),
    "tag": "A Ritual for You",
    "image": "/newsletter/newsletter-hair-therapy.webp",
    "imageAlt": "Wynn Essentials hair therapy editorial",
    "eyebrow": "You Belong on the Gift List",
    "title": "Save a little softness<br>for yourself.",
    "body": "Between giving, gathering and getting everything done, your own ritual still matters. Choose the moisture, scalp or styling essential that brings you back to yourself.",
    "cta": "Choose Your Self-Care",
    "href": "/",
    "background": "#6f2031",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": "Free standard U.S. shipping applies December 19, 2026. Christmas delivery is not promised. Excludes any expedited-shipping charges."
  },
  {
    "id": "reset-2026",
    "name": "The Post-Holiday Reset",
    "subject": "After the styling comes the reset—20% off haircare",
    "preheader": "Replenish moisture and bring your routine back into balance.",
    "scheduledAt": new Date("2026-12-26T17:00:00Z"),
    "expiresAt": new Date("2026-12-27T17:00:00Z"),
    "tag": "The Post-Holiday Reset",
    "image": "/newsletter/newsletter-revaivl-mask.webp",
    "imageAlt": "Woman holding Wynn Essentials Revaivl Deep Conditioning Hair Mask",
    "eyebrow": "The Reset Issue",
    "title": "Holiday hair had its moment.<br>Now restore the practice.",
    "body": "After heat, protective styling and busy days, return to the essentials: cleanse gently, condition deeply, restore moisture and seal with intention.",
    "cta": "Reset Your Routine",
    "href": "/",
    "background": "#526a48",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "RESET20",
    "terms": "Excludes Boho Hair, gift cards and previously discounted merchandise. Cannot be combined."
  },
  {
    "id": "newyear-2026",
    "name": "Your Next Chapter",
    "subject": "New year. New practice. A $20.27 credit awaits.",
    "preheader": "Spend $100 and begin 2027 with something to return to.",
    "scheduledAt": new Date("2026-12-31T17:00:00Z"),
    "expiresAt": new Date("2027-01-01T17:00:00Z"),
    "tag": "Your Next Chapter",
    "image": "/newsletter/newsletter-nourish-robe.webp",
    "imageAlt": "Woman in a copper robe holding Wynn Essentials Nourish oil",
    "eyebrow": "New Year, New Practice",
    "title": "Not a resolution.<br>A ritual you can return to.",
    "body": "Begin 2027 with a routine built around what your hair actually needs. Spend $100 today and receive a $20.27 Wynn Essentials credit for your next chapter.",
    "cta": "Build Your 2027 Practice",
    "href": "/find-your-routine",
    "background": "#1d1815",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "$20.27 CREDIT",
    "terms": "Qualifying subtotal must reach $100 after discounts and before shipping and tax. Credit delivery, redemption dates and minimum purchase requirements must be confirmed before scheduling."
  },
  {
    "id": "winter-2027",
    "name": "The Winter Moisture Issue",
    "subject": "Your winter moisture reset starts here",
    "preheader": "Cold air outside. Intentional moisture inside.",
    "scheduledAt": new Date("2027-01-08T17:00:00Z"),
    "expiresAt": new Date("2027-01-09T17:00:00Z"),
    "tag": "The Winter Moisture Issue",
    "image": "/newsletter/newsletter-hydrate-pink.webp",
    "imageAlt": "Wynn Essentials Hydrate in a vibrant pink winter editorial",
    "eyebrow": "Winter Changes the Assignment",
    "title": "More moisture.<br>Less guesswork.",
    "body": "Cold air, indoor heat and protective styles can leave textured hair asking for more. Reset with a practice that replenishes water, restores softness and seals in what your strands need.",
    "cta": "Shop the Winter Reset",
    "href": "/hair-wellness-bundle",
    "background": "#315878",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "mlk-2027",
    "name": "A Day of Reflection",
    "subject": "The practice of building something that serves",
    "preheader": "A reflection from Wynn Essentials on purpose, community and progress.",
    "scheduledAt": new Date("2027-01-18T17:00:00Z"),
    "expiresAt": new Date("2027-01-19T17:00:00Z"),
    "tag": "A Day of Reflection",
    "image": "/editorial/wellness-ritual.jpeg",
    "imageAlt": "Wynn Essentials products arranged as a thoughtful daily wellness ritual",
    "eyebrow": "Martin Luther King Jr. Day",
    "title": "Purpose becomes powerful<br>when it serves others.",
    "body": "Today, we reflect on the responsibility to build with intention, care for our community and keep moving toward a future where Black ideas, Black wellness and Black-owned businesses have room to flourish.",
    "cta": "Our Practice & Purpose",
    "href": "/",
    "background": "#6b4634",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "history-2027",
    "name": "Rooted in Care",
    "subject": "Our history lives in the way we care",
    "preheader": "Black hair care is memory, creativity, knowledge and practice.",
    "scheduledAt": new Date("2027-02-01T17:00:00Z"),
    "expiresAt": new Date("2027-02-02T17:00:00Z"),
    "tag": "Rooted in Care",
    "image": "/editorial/relief-braids.jpeg",
    "imageAlt": "Woman with blonde braids holding Wynn Essentials Relief oil",
    "eyebrow": "More Than Hair",
    "title": "Every crown carries<br>a history of its own.",
    "body": "Black hair has always held more than style. It carries ingenuity, identity, protection, expression and the knowledge passed between generations. This month, we honor the hands, rituals and stories that shaped the practice.",
    "cta": "Explore Our Story",
    "href": "/",
    "background": "#352018",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "love-2027",
    "name": "The Love Your Hair Issue",
    "subject": "Love your hair in the language it understands",
    "preheader": "Moisture, patience, protection and a practice made personal.",
    "scheduledAt": new Date("2027-02-07T17:00:00Z"),
    "expiresAt": new Date("2027-02-08T17:00:00Z"),
    "tag": "The Love Your Hair Issue",
    "image": "/shoppable/pink-scarf.jpeg",
    "imageAlt": "Woman wearing a pink Wynn Essentials scarf with her curls visible",
    "eyebrow": "A Love Letter to Your Crown",
    "title": "Listen closely.<br>Your hair tells you what it needs.",
    "body": "Sometimes love looks like moisture before styling. Sometimes it looks like a gentle cleanse, a deep condition or leaving your edges alone. Build a practice that responds instead of forcing.",
    "cta": "Find Your Hair’s Love Language",
    "href": "/find-your-routine",
    "background": "#9c3f68",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "LOVE20",
    "terms": "Eligible moisture products and final promotional terms to be confirmed before scheduling. Cannot be combined."
  },
  {
    "id": "valentine-2027",
    "name": "With Love, Wynn Essentials",
    "subject": "Your Valentine’s ritual ships free today",
    "preheader": "Choose something soft, restorative and entirely for you.",
    "scheduledAt": new Date("2027-02-14T17:00:00Z"),
    "expiresAt": new Date("2027-02-15T17:00:00Z"),
    "tag": "With Love, Wynn Essentials",
    "image": "/collections/soft-life-bonnet-lifestyle-pink.webp",
    "imageAlt": "Soft Life Bonnet styled in a romantic pink editorial",
    "eyebrow": "A Gift From You, to You",
    "title": "Softness is a form<br>of self-respect.",
    "body": "Protect your hair at night, restore moisture when it asks and make room for a ritual that belongs only to you. Today, your self-care order ships free.",
    "cta": "Shop Your Valentine",
    "href": "/",
    "background": "#d59aae",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": "Valid February 14, 2027. Free standard U.S. shipping only; expedited shipping is excluded."
  },
  {
    "id": "spotlight-2027",
    "name": "Black-Owned Beauty Spotlight",
    "subject": "What your support makes possible",
    "preheader": "Every Wynn Essentials order helps a Black-owned practice keep growing.",
    "scheduledAt": new Date("2027-02-21T17:00:00Z"),
    "expiresAt": new Date("2027-02-22T17:00:00Z"),
    "tag": "Black-Owned Beauty Spotlight",
    "image": "/newsletter/newsletter-oil-trio-pouch.webp",
    "imageAlt": "Wynn Essentials oil trio and branded pouch",
    "eyebrow": "Behind Every Bottle",
    "title": "You are not just buying haircare.<br>You are backing a vision.",
    "body": "Your support helps Wynn Essentials develop thoughtful products, create imagery that celebrates textured hair and build a brand where healthy-hair education and beautiful presentation belong together.",
    "cta": "Support Black-Owned Beauty",
    "href": "/",
    "background": "#31241d",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "women-2027",
    "name": "Women’s History Month",
    "subject": "Women’s History Month begins with the women who build",
    "preheader": "Wynn Essentials is woman-owned, purpose-led and rooted in textured-hair care.",
    "scheduledAt": new Date("2027-03-01T17:00:00Z"),
    "expiresAt": new Date("2027-03-02T17:00:00Z"),
    "tag": "Women’s History Month",
    "image": "/editorial/uplyft-model.jpeg",
    "imageAlt": "Woman holding Wynn Essentials Uplyft conditioner",
    "eyebrow": "Woman-Owned. Practice-Led.",
    "title": "She imagined more.<br>Then she built it.",
    "body": "This month, we celebrate the women who turn lived experience into ideas, ideas into businesses and businesses into resources their communities can use. Wynn Essentials is part of that continuing story.",
    "cta": "Discover Wynn Essentials",
    "href": "/",
    "background": "#65426d",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "iwd-2027",
    "name": "International Women’s Day",
    "subject": "Here’s to the women who make care possible",
    "preheader": "Today we celebrate the rituals, knowledge and community women carry forward.",
    "scheduledAt": new Date("2027-03-08T17:00:00Z"),
    "expiresAt": new Date("2027-03-09T17:00:00Z"),
    "tag": "International Women’s Day",
    "image": "/shoppable/bonnet-group.png",
    "imageAlt": "A group of women wearing Wynn Essentials Soft Life Bonnets",
    "eyebrow": "Care Is Collective",
    "title": "When women care for women,<br>knowledge keeps moving.",
    "body": "From kitchen conversations to salon chairs, wash-day lessons to business blueprints, women have always created spaces where care can be shared. Today, we honor that generosity.",
    "cta": "Celebrate With Us",
    "href": "/",
    "background": "#a54155",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "spring-2027",
    "name": "The Spring Reset",
    "subject": "Spring starts with a clean scalp and a lighter routine",
    "preheader": "Reset buildup, restore moisture and make room for what’s next.",
    "scheduledAt": new Date("2027-03-20T16:00:00Z"),
    "expiresAt": new Date("2027-03-21T16:00:00Z"),
    "tag": "The Spring Reset",
    "image": "/editorial/lathyr-foam.jpeg",
    "imageAlt": "Wynn Essentials Lathyr cleansing foam editorial",
    "eyebrow": "Clear the Buildup",
    "title": "A fresh season calls<br>for a clean foundation.",
    "body": "Begin at the scalp. Cleanse away winter buildup without stripping, condition with intention and bring lightweight moisture back into your routine.",
    "cta": "Start the Spring Reset",
    "href": "/hair-wellness-bundle",
    "background": "#47644c",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "SPRING20",
    "terms": "Eligible products and final terms to be confirmed before scheduling. Cannot be combined."
  },
  {
    "id": "easter-2027",
    "name": "Spring Gifting",
    "subject": "A bright little spring surprise",
    "preheader": "Fresh color, thoughtful care and 15% off selected gifts.",
    "scheduledAt": new Date("2027-03-28T16:00:00Z"),
    "expiresAt": new Date("2027-03-29T16:00:00Z"),
    "tag": "Spring Gifting",
    "image": "/shoppable/relief-gift.jpeg",
    "imageAlt": "Wynn Essentials Relief oil and linen gift bag presented in bright pink packaging",
    "eyebrow": "Something Better Than Candy",
    "title": "Fill their basket<br>with a beautiful ritual.",
    "body": "Choose a soft bonnet, a nourishing oil or a complete hair wellness routine—spring gifts designed to last longer than the chocolate.",
    "cta": "Shop Spring Gifts",
    "href": "/",
    "background": "#f0b6c9",
    "foreground": "#211813",
    "accent": "#77394a",
    "offer": "SPRINGGIFT15",
    "terms": "Eligible products and promotional dates to be confirmed. Excludes Boho Hair preorders and gift cards. Cannot be combined."
  },
  {
    "id": "prep-2027",
    "name": "Protective-Style Prep",
    "subject": "The finishing touch your spring styles deserve",
    "preheader": "Smooth, shape and polish with hydrating hold.",
    "scheduledAt": new Date("2027-04-11T16:00:00Z"),
    "expiresAt": new Date("2027-04-12T16:00:00Z"),
    "tag": "The Spring Styling Edit",
    "image": "/editorial/edge-control.jpeg",
    "imageAlt": "Wynn Essentials Edge Control held against a soft lavender background",
    "eyebrow": "Smooth. Shape. Set.",
    "title": "The style is<br>in the details.",
    "body": "From sleek ponytails and polished braids to laid edges and clean finishing, Wynn Essentials Edge Control gives your style hydrating hold without making care an afterthought.",
    "cta": "Shop Edge Control",
    "href": "/products/edge-control",
    "background": "#3e5a78",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "earth-2027",
    "name": "Rooted in the Ritual",
    "subject": "A closer look at what goes into your practice",
    "preheader": "Botanical ingredients, thoughtful formulas and care with purpose.",
    "scheduledAt": new Date("2027-04-22T16:00:00Z"),
    "expiresAt": new Date("2027-04-23T16:00:00Z"),
    "tag": "Rooted in the Ritual",
    "image": "/shoppable/grow-model.jpeg",
    "imageAlt": "Woman with full textured hair holding Wynn Essentials Grow botanical oil",
    "eyebrow": "Know What Supports Your Hair",
    "title": "Intentional care begins<br>with understanding the formula.",
    "body": "Today is an invitation to look closer: at the ingredients you use, the purpose each product serves and the way a consistent routine can help you use only what your hair needs.",
    "cta": "Explore the Ingredients",
    "href": "/",
    "background": "#344e36",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "mom-2027",
    "name": "The Mother’s Day Gift Guide",
    "subject": "For every way she pours into you",
    "preheader": "Soft-life gifts and thoughtful rituals for Mother’s Day.",
    "scheduledAt": new Date("2027-05-02T16:00:00Z"),
    "expiresAt": new Date("2027-05-03T16:00:00Z"),
    "tag": "The Mother’s Day Gift Guide",
    "image": "/collections/soft-life-bonnet-lifestyle-purple.webp",
    "imageAlt": "Woman resting in a purple Wynn Essentials Soft Life Bonnet",
    "eyebrow": "Give Her a Softer Moment",
    "title": "She deserves care<br>that feels like care.",
    "body": "For the woman who makes room for everyone else, choose a gift that invites her to slow down: a soft bonnet, a nourishing oil or a full wash-day ritual made with intention.",
    "cta": "Shop Gifts for Her",
    "href": "/",
    "background": "#80516f",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "last-2027",
    "name": "Mother’s Day",
    "subject": "A little more care for the women who give so much",
    "preheader": "Mother’s Day gifting, with complimentary shipping today.",
    "scheduledAt": new Date("2027-05-09T15:00:00Z"),
    "expiresAt": new Date("2027-05-10T15:00:00Z"),
    "tag": "Mother’s Day",
    "image": "/shoppable/nourish-model.jpeg",
    "imageAlt": "Woman holding Wynn Essentials Nourish oil",
    "eyebrow": "A Gift for Her Ritual",
    "title": "Celebrate the care<br>she gives every day.",
    "body": "Send a little softness, moisture and intention her way. Today, complimentary shipping makes it easier to choose something meaningful—even if the gift arrives after the celebration.",
    "cta": "Choose Her Gift",
    "href": "/",
    "background": "#dca6ae",
    "foreground": "#211813",
    "accent": "#77394a",
    "offer": "FREE SHIPPING",
    "terms": "Final shipping terms and delivery language to be confirmed before scheduling. Cannot be combined."
  },
  {
    "id": "grad-2027",
    "name": "Graduation Season",
    "subject": "Your next chapter deserves healthy-hair energy",
    "preheader": "Graduation gifts for every new beginning.",
    "scheduledAt": new Date("2027-05-23T16:00:00Z"),
    "expiresAt": new Date("2027-05-24T16:00:00Z"),
    "tag": "Graduation Season",
    "image": "/shoppable/grow-sleek.jpeg",
    "imageAlt": "Woman with a sleek healthy-hair style",
    "eyebrow": "For Everything Ahead",
    "title": "New chapter.<br>Same beautiful roots.",
    "body": "Celebrate the graduate with rituals that can move with her—from early mornings and first interviews to every milestone still waiting ahead.",
    "cta": "Shop Graduation Gifts",
    "href": "/",
    "background": "#315f79",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "NEXTCHAPTER15",
    "terms": "Eligible products and promotional dates to be confirmed. Excludes Boho Hair preorders and gift cards. Cannot be combined."
  },
  {
    "id": "memorial-2027",
    "name": "The Summer Hair Edit",
    "subject": "Summer starts with moisture",
    "preheader": "Lightweight hydration and 20% off eligible warm-weather essentials.",
    "scheduledAt": new Date("2027-05-31T16:00:00Z"),
    "expiresAt": new Date("2027-06-01T16:00:00Z"),
    "tag": "The Summer Hair Edit",
    "image": "/shoppable/hydrate-nourish.jpeg",
    "imageAlt": "Wynn Essentials Hydrate and Nourish summer moisture routine",
    "eyebrow": "Hydrate. Seal. Go.",
    "title": "Keep the moisture.<br>Lose the heavy routine.",
    "body": "Warm days call for a lighter practice. Refresh thirsty strands with Hydrate, seal in softness with Nourish and give your scalp the consistent care it needs.",
    "cta": "Shop Summer Essentials",
    "href": "/",
    "background": "#8f2d2b",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "SUMMER20",
    "terms": "Eligible products and promotional dates to be confirmed. Excludes Boho Hair preorders and gift cards. Cannot be combined."
  },
  {
    "id": "juneteenth-2027",
    "name": "Juneteenth",
    "subject": "Our freedom, our roots, our legacy",
    "preheader": "This Juneteenth, we honor the care and knowledge carried forward.",
    "scheduledAt": new Date("2027-06-19T16:00:00Z"),
    "expiresAt": new Date("2027-06-20T16:00:00Z"),
    "tag": "Juneteenth",
    "image": "/collections/heritage-hold-estate-flatlay.webp",
    "imageAlt": "Wynn Essentials Heritage Hold collection",
    "eyebrow": "Rooted in Legacy",
    "title": "What we carry forward<br>becomes our inheritance.",
    "body": "Our hair rituals hold memory, creativity, resilience and care. Today we honor the generations who protected that knowledge—and the freedom to define beauty, wellness and ownership on our own terms.",
    "cta": "Read Our Story",
    "href": "/",
    "background": "#352018",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "dad-2027",
    "name": "Father’s Day",
    "subject": "A simple routine for the men who keep showing up",
    "preheader": "Straightforward scalp and moisture care for Father’s Day.",
    "scheduledAt": new Date("2027-06-20T16:00:00Z"),
    "expiresAt": new Date("2027-06-21T16:00:00Z"),
    "tag": "Father’s Day",
    "image": "/shoppable/grow-lineup.png",
    "imageAlt": "Wynn Essentials Grow oil lineup",
    "eyebrow": "Simple Care. Consistent Practice.",
    "title": "A better scalp routine<br>doesn’t need ten steps.",
    "body": "Keep it straightforward: apply a few drops, massage the scalp and repeat consistently. A practical ritual for dads, partners, mentors—and every man ready to care for his crown.",
    "cta": "Shop Grow",
    "href": "/products/grow",
    "background": "#395344",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "FORHIM15",
    "terms": "Eligible products and promotional dates to be confirmed. Excludes Boho Hair preorders and gift cards. Cannot be combined."
  },
  {
    "id": "freedom-2027",
    "name": "Summer Hair, Your Way",
    "subject": "Your summer hair deserves a little freedom, too",
    "preheader": "Lightweight moisture, easy styles and 15% off eligible summer care.",
    "scheduledAt": new Date("2027-07-04T16:00:00Z"),
    "expiresAt": new Date("2027-07-05T16:00:00Z"),
    "tag": "Summer Hair, Your Way",
    "image": "/shoppable/nourish-orange.png",
    "imageAlt": "Wynn Essentials Nourish oil in a bright summer setting",
    "eyebrow": "Wear It Free",
    "title": "Your texture.<br>Your ritual. Your rules.",
    "body": "However you wear your hair this summer, keep the foundation cared for. Refresh moisture, protect your strands and choose the routine that works for your life.",
    "cta": "Shop Summer Hair Care",
    "href": "/",
    "background": "#345c83",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "FREEDOM15",
    "terms": "Eligible products and dates to be confirmed. Excludes Boho Hair preorders and gift cards. Cannot be combined."
  },
  {
    "id": "hydrate-2027",
    "name": "The Mid-Summer Moisture Check",
    "subject": "Your hair is asking for water",
    "preheader": "A simple two-step answer for dry summer strands.",
    "scheduledAt": new Date("2027-07-18T16:00:00Z"),
    "expiresAt": new Date("2027-07-19T16:00:00Z"),
    "tag": "The Mid-Summer Moisture Check",
    "image": "/shoppable/hydrate-results.png",
    "imageAlt": "Hydrated textured hair results",
    "eyebrow": "Refresh + Seal",
    "title": "Heat changes the routine.<br>Moisture keeps it grounded.",
    "body": "Mist Hydrate through thirsty strands, then seal that moisture with a small amount of Nourish. Two lightweight steps that help your hair stay soft without weighing down the style.",
    "cta": "Build the Moisture Duo",
    "href": "/",
    "background": "#e68679",
    "foreground": "#211813",
    "accent": "#77394a",
    "offer": "",
    "terms": ""
  },
  {
    "id": "blackbiz-2027",
    "name": "Black Business Month",
    "subject": "What your support makes possible",
    "preheader": "Black Business Month begins with community, ownership and intention.",
    "scheduledAt": new Date("2027-08-01T16:00:00Z"),
    "expiresAt": new Date("2027-08-02T16:00:00Z"),
    "tag": "Black Business Month",
    "image": "/shoppable/heritage-hold-street.jpeg",
    "imageAlt": "Wynn Essentials styling products photographed in a bold street-style scene",
    "eyebrow": "More Than a Purchase",
    "title": "You help a Black-owned<br>vision keep growing.",
    "body": "Every order supports the work behind the formula: thoughtful product development, textured-hair education and a woman-owned business built to make healthy-hair care feel clear and intentional.",
    "cta": "Support Wynn Essentials",
    "href": "/",
    "background": "#2b201b",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "school-2027",
    "name": "Back-to-School Hair",
    "subject": "School mornings need an easier hair plan",
    "preheader": "Prep at night, refresh in the morning and protect the routine.",
    "scheduledAt": new Date("2027-08-08T16:00:00Z"),
    "expiresAt": new Date("2027-08-09T16:00:00Z"),
    "tag": "Back-to-School Hair",
    "image": "/shoppable/bonnet-bedroom.png",
    "imageAlt": "Soft Life Bonnet in a cozy bedroom setting",
    "eyebrow": "Less Rush. More Routine.",
    "title": "Make tomorrow morning<br>easier tonight.",
    "body": "Moisturize, style and cover before bed. A consistent nighttime routine can help preserve softness and make early school mornings feel a little less chaotic.",
    "cta": "Build the School-Night Routine",
    "href": "/",
    "background": "#715884",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "SCHOOL15",
    "terms": "Eligible products and dates to be confirmed. Excludes Boho Hair preorders and gift cards. Cannot be combined."
  },
  {
    "id": "protect-2027",
    "name": "The Protective-Style Practice",
    "subject": "Protective style season starts underneath",
    "preheader": "Cleanse, condition and moisturize before your next install.",
    "scheduledAt": new Date("2027-08-15T16:00:00Z"),
    "expiresAt": new Date("2027-08-16T16:00:00Z"),
    "tag": "The Protective-Style Practice",
    "image": "/collections/heritage-hold-lifestyle.jpeg",
    "imageAlt": "Polished protective hairstyle",
    "eyebrow": "Care Before the Chair",
    "title": "The style may be protective.<br>The prep is still essential.",
    "body": "Start with a clean scalp, conditioned strands and balanced moisture before the install. Then maintain the scalp and exposed hair throughout the style—without product overload.",
    "cta": "Read the Braiding & Care Guide",
    "href": "/braiding-hair",
    "background": "#a73e76",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "",
    "terms": ""
  },
  {
    "id": "reset-2027",
    "name": "The End-of-Summer Reset",
    "subject": "Before summer ends, reset the routine",
    "preheader": "Clear buildup, replenish moisture and head into fall with intention.",
    "scheduledAt": new Date("2027-08-29T16:00:00Z"),
    "expiresAt": new Date("2027-08-30T16:00:00Z"),
    "tag": "The End-of-Summer Reset",
    "image": "/shoppable/lathyr-bag.jpeg",
    "imageAlt": "Wynn Essentials Lathyr cleanser presented as part of a fresh reset ritual",
    "eyebrow": "Return to the Foundation",
    "title": "Wash away the summer.<br>Keep the healthy habits.",
    "body": "Sun, sweat, swimming and protective styles can leave buildup behind. Give your scalp a thorough—but gentle—cleanse, restore moisture and prepare your routine for the season ahead.",
    "cta": "Start the Reset",
    "href": "/hair-wellness-bundle",
    "background": "#526a48",
    "foreground": "#fff",
    "accent": "#ffb8dc",
    "offer": "FREE SHIPPING",
    "terms": "Final shipping terms and dates to be confirmed before scheduling. Cannot be combined."
  }
] as const;
