import { BRAND, BUSINESS_ADDRESS, RESPONSIVE_STYLE, button, emailUrl, esc } from "./email-brand";
import { unsubscribeUrl } from "./unsubscribe";

export type FallCampaignId = "fall-reset-2026" | "national-hair-day-2026";

export const fallCampaigns = [
  { id: "fall-reset-2026", name: "Fall Reset · Healthy Hair Is a Practice", subject: "Fall back into your healthiest ritual", scheduledAt: new Date("2026-09-22T16:00:00Z"), expiresAt: new Date("2026-09-23T16:00:00Z") },
  { id: "national-hair-day-2026", name: "National Hair Day · Celebrate Your Story", subject: "Celebrate the hair that tells your story", scheduledAt: new Date("2026-10-01T16:00:00Z"), expiresAt: new Date("2026-10-02T16:00:00Z") },
] as const;

const logo = `<img src="${emailUrl("/email/wynn-essentials-logo.png")}" width="230" alt="Wynn Essentials" style="display:block;width:230px;max-width:70%;height:auto;margin:0 auto">`;
const image = (src: string, alt: string) => `<img class="fluid" src="${emailUrl(src)}" width="600" alt="${esc(alt)}" style="display:block;width:100%;max-width:600px;height:auto;border:0">`;
const heading = (copy: string, color = BRAND.black) => `<h1 class="h-lg" style="margin:14px 0 18px;font-family:${BRAND.serif};font-size:48px;line-height:.98;font-weight:normal;letter-spacing:-.04em;color:${color}">${copy}</h1>`;
const brand = (tag: string) => `<tr><td style="padding:24px 22px 18px;text-align:center;background:#fff">${logo}<p style="margin:7px 0 0;font:9px ${BRAND.sans};letter-spacing:.3em;text-transform:uppercase">${tag}</p></td></tr>`;
const footer = (email: string, note = "") => `<tr><td class="px" style="padding:28px 34px;background:#f4eee6;text-align:center;font-family:${BRAND.sans};font-size:10px;line-height:18px;color:#675d54">WYNN ESSENTIALS · Healthy Hair Is a Practice${note}<br>${BUSINESS_ADDRESS}<br><a href="${emailUrl("/")}" style="color:#675d54">Shop</a> · <a href="${emailUrl("/#routine-finder")}" style="color:#675d54">Find Your Routine</a> · <a href="${unsubscribeUrl(email)}" style="color:#675d54">Unsubscribe</a></td></tr>`;

function shell(preheader: string, rows: string) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>${RESPONSIVE_STYLE}</style></head><body style="margin:0;background:#e8e1d8"><div style="display:none;max-height:0;overflow:hidden;opacity:0">${esc(preheader)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;background:#e8e1d8"><tr><td align="center" style="padding:24px 10px"><table class="wrap" role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px;max-width:600px;background:#fff;border-collapse:collapse">${rows}</table></td></tr></table></body></html>`;
}

function fallReset(email: string) {
  const steps = [["01","Cleanse with Lathyr","Reset the scalp and remove buildup without stripping moisture."],["02","Condition with Uplyft","Bring softness and deep moisture back to clean, damp strands."],["03","Refresh with Hydrate","Replenish dry areas with lightweight leave-in moisture."],["04","Seal with Nourish","Help hold onto the moisture you restored."]]
    .map(([n,h,p]) => `<tr><td style="padding:16px 18px;border-bottom:1px solid #ded1c3"><b style="color:${BRAND.pink};font:italic 25px ${BRAND.serif}">${n}</b><strong style="display:block;margin:5px 0;font:12px ${BRAND.sans};letter-spacing:.08em;text-transform:uppercase">${h}</strong><span style="font:12px/19px ${BRAND.sans};color:#665c53">${p}</span></td></tr>`).join("");
  return shell("A new season for your healthiest hair ritual.", `<tr><td style="padding:10px;background:#5f4032;color:#fff;text-align:center;font:900 10px ${BRAND.sans};letter-spacing:.16em;text-transform:uppercase">The Fall Reset Issue · Healthy Hair Is a Practice</td></tr>${brand("Healthy Hair Is a Practice")}<tr><td>${image("/collections/hair-wellness-bundle-official-1.webp", "Wynn Essentials Hair Wellness Bundle")}</td></tr><tr><td class="px" style="padding:40px 34px 44px;background:#f8f1e7;text-align:center"><p style="margin:0;color:${BRAND.pink};font:900 10px ${BRAND.sans};letter-spacing:.2em;text-transform:uppercase">A new season for your routine</p>${heading("Fall back into<br>your healthiest ritual.")}<p style="max-width:475px;margin:0 auto 24px;color:#5c5149;font:14px/24px ${BRAND.sans}">Cooler air asks more of your moisture routine. Begin the season with a thoughtful reset built around cleansing, conditioning, daily hydration and sealing in every drop of care.</p>${button("Shop the Hair Wellness Bundle", emailUrl("/products/hair-wellness-bundle"), "center")}</td></tr><tr><td class="px" style="padding:39px 30px;background:#f4e9dc"><h2 class="h-md" style="margin:0 0 8px;text-align:center;font:normal 36px ${BRAND.serif}">Your fall moisture rhythm</h2><p style="margin:0 0 24px;text-align:center;font:13px/21px ${BRAND.sans};color:#665b53">Four essentials. One consistent practice.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#fff">${steps}</table></td></tr><tr><td style="padding:42px 32px;background:#77806a;color:#fff;text-align:center"><p style="margin:0 0 12px;font:italic 30px/1.25 ${BRAND.serif}">“The season changes. Your commitment to healthy hair stays.”</p><span style="font:900 9px ${BRAND.sans};letter-spacing:.2em;text-transform:uppercase">No discount · just a better ritual</span></td></tr>${footer(email)}`);
}

function hairDay(email: string) {
  const products = [["/products/hydrate-official.png","MOISTURE","Refresh thirsty strands with Hydrate, then seal with Nourish."],["/products/uplyft-official.jpg","WASH DAY","Cleanse with Lathyr and condition with Uplyft or Revaivl."],["/collections/boho-card-bohemian-curl.webp","PROTECTIVE STYLE","Bring your dream Boho Hair texture to your next install."]]
    .map(([src,h,p]) => `<tr><td style="width:120px;padding:9px 0;border-bottom:1px solid #eaded3">${image(src,h)}</td><td style="padding:14px;border-bottom:1px solid #eaded3"><b style="font:11px ${BRAND.sans}">${h}</b><span style="display:block;margin-top:5px;color:#746960;font:10px/16px ${BRAND.sans}">${p}</span></td></tr>`).join("");
  return shell("Celebrate every texture with free shipping for National Hair Day.", `<tr><td style="padding:12px;background:${BRAND.pink};color:#fff;text-align:center;font:900 11px ${BRAND.sans};letter-spacing:.17em;text-transform:uppercase">National Hair Day · Free Shipping</td></tr>${brand("Every texture deserves a practice")}<tr><td>${image("/collections/wynn-essentials-natural-girlies.webp", "Woman celebrating healthy textured hair")}</td></tr><tr><td class="px" style="padding:40px 34px 44px;background:#963f29;color:#fff;text-align:center"><p style="margin:0;color:#ffc19d;font:900 10px ${BRAND.sans};letter-spacing:.2em;text-transform:uppercase">October 1 · National Hair Day</p>${heading("Celebrate the hair<br>that tells your story.", "#fffaf3")}<p style="max-width:465px;margin:0 auto 24px;color:#f8e7d8;font:14px/24px ${BRAND.sans}">From wash day to protective styles, curls to braids, healthy hair is not one look—it’s a practice made personal. Today, explore the full Wynn Essentials collection with free shipping.</p>${button("Shop With Free Shipping", emailUrl("/"), "center", BRAND.pink, BRAND.white)}</td></tr><tr><td style="padding:17px;background:#caae86;color:#fff;text-align:center;font:900 13px ${BRAND.sans};letter-spacing:.14em;text-transform:uppercase">Free shipping · One day only</td></tr><tr><td class="px" style="padding:38px 30px"><h2 class="h-md" style="margin:0 0 22px;text-align:center;font:normal 36px ${BRAND.serif}">Choose what your hair needs</h2><table role="presentation" width="100%" cellpadding="0" cellspacing="0">${products}</table></td></tr><tr><td style="padding:42px 32px;background:#fff0f8;text-align:center"><h2 class="h-md" style="margin:0 0 11px;color:#963f29;font:normal 37px ${BRAND.serif}">Your hair. Your ritual. Your story.</h2><p style="margin:0 auto 22px;max-width:450px;color:#6b4b43;font:13px/21px ${BRAND.sans}">Celebrate with the essentials that support your texture, your goals and the way you choose to wear your crown.</p>${button("Explore Wynn Essentials", emailUrl("/"), "center", BRAND.pink, BRAND.white)}</td></tr>${footer(email, "<br>Free standard U.S. shipping available October 1, 2026.")}`);
}

export function fallCampaignEmail(id: FallCampaignId, email: string) {
  const campaign = fallCampaigns.find(item => item.id === id)!;
  const html = id === "fall-reset-2026" ? fallReset(email) : hairDay(email);
  return { subject: campaign.subject, html, text: `${campaign.subject}\n\nShop Wynn Essentials: ${emailUrl("/")}\nUnsubscribe: ${unsubscribeUrl(email)}` };
}
