import { BRAND, BUSINESS_ADDRESS, RESPONSIVE_STYLE, button, emailUrl, esc } from "./email-brand";
import { unsubscribeUrl } from "./unsubscribe";

export type LaborDayCampaignId = "labor-day-2026-reset" | "labor-day-2026-free-shipping" | "labor-day-2026-final-hours";

export const laborDayCampaigns = [
  { id: "labor-day-2026-reset", name: "Labor Day · The Reset Issue", subject: "Your hair called. It’s ready to reset.", scheduledAt: new Date("2026-09-01T16:00:00Z"), expiresAt: new Date("2026-09-02T16:00:00Z") },
  { id: "labor-day-2026-free-shipping", name: "Labor Day · Wash-Day Ritual", subject: "Free shipping: make wash day a ritual", scheduledAt: new Date("2026-09-04T16:00:00Z"), expiresAt: new Date("2026-09-07T07:00:00Z") },
  { id: "labor-day-2026-final-hours", name: "Labor Day · Final Hours", subject: "Final hours: 20% off ends tonight", scheduledAt: new Date("2026-09-07T16:00:00Z"), expiresAt: new Date("2026-09-08T07:00:00Z") },
] as const;

const logo = `<img src="${emailUrl("/email/wynn-essentials-logo.png")}" width="230" alt="Wynn Essentials" style="display:block;width:230px;max-width:70%;height:auto;margin:0 auto">`;
const image = (src: string, alt: string) => `<img class="fluid" src="${emailUrl(src)}" width="600" alt="${esc(alt)}" style="display:block;width:100%;max-width:600px;height:auto">`;
const title = (copy: string) => `<h1 class="h-lg" style="margin:16px 0 18px;font-family:${BRAND.serif};font-size:48px;line-height:.98;font-weight:normal;letter-spacing:-.04em;color:${BRAND.black}">${copy}</h1>`;
const footer = (email: string, extra = "") => `<tr><td class="px" style="padding:28px 34px;background:#f4eee6;text-align:center;font-family:${BRAND.sans};font-size:10px;line-height:18px;color:#675d54">WYNN ESSENTIALS · Healthy Hair Is a Practice${extra}<br>${BUSINESS_ADDRESS}<br><a href="${emailUrl("/")}" style="color:#675d54">Shop</a> · <a href="${emailUrl("/#routine-finder")}" style="color:#675d54">Find Your Routine</a> · <a href="${unsubscribeUrl(email)}" style="color:#675d54">Unsubscribe</a></td></tr>`;

function shell(preheader: string, rows: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>${RESPONSIVE_STYLE}</style></head><body style="margin:0;background:#e8e1d8"><div style="display:none;max-height:0;overflow:hidden;opacity:0">${esc(preheader)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;background:#e8e1d8"><tr><td align="center" style="padding:24px 10px"><table class="wrap" role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px;max-width:600px;background:#fff;border-collapse:collapse">${rows}</table></td></tr></table></body></html>`;
}

const brandRow = (tag: string) => `<tr><td style="padding:24px 22px 18px;text-align:center;background:#fff">${logo}<p style="margin:7px 0 0;font:9px ${BRAND.sans};letter-spacing:.3em;text-transform:uppercase">${tag}</p></td></tr>`;
const pinkButton = (label: string, url: string) => button(label, url, "center", BRAND.pink, BRAND.white);

function reset(email: string) {
  const steps = [
    ["01", "Lathyr · Cleanse", "Gently wash away buildup and give your routine a fresh foundation."],
    ["02", "Uplyft · Condition", "Restore moisture and softness with the bundle’s moisture-rich conditioner."],
    ["03", "Hydrate · Replenish", "Bring moisture and softness back to thirsty strands."],
    ["04", "Nourish · Seal", "Finish the ritual by helping seal in the moisture you just restored."],
  ].map(([n, h, p]) => `<tr><td style="padding:15px 18px;border-bottom:1px solid #ddd0c0"><b style="color:${BRAND.pink};font:italic 24px ${BRAND.serif}">${n}</b><strong style="display:block;margin:5px 0;font:12px ${BRAND.sans};letter-spacing:.08em;text-transform:uppercase">${h}</strong><span style="font:12px/19px ${BRAND.sans};color:#665c53">${p}</span></td></tr>`).join("");
  return shell("A four-step end-of-summer reset for your healthiest season yet.", `<tr><td style="padding:10px 16px;background:#17130f;color:#fff;text-align:center;font:10px ${BRAND.sans};letter-spacing:.15em;text-transform:uppercase">End-of-summer edition · Healthy Hair Is a Practice</td></tr>${brandRow("Healthy Hair Is a Practice")}<tr><td>${image("/email/labor-day-reset.jpg", "Wynn Essentials Hair Wellness Bundle lineup")}</td></tr><tr><td class="px" style="padding:36px 34px 42px;text-align:center"><p style="margin:0;font:800 11px ${BRAND.sans};letter-spacing:.2em;text-transform:uppercase">Labor Day · The Reset Issue</p>${title("Your hair called.<br>It’s ready to reset.")}<p style="margin:0 auto 25px;max-width:475px;font:15px/25px ${BRAND.sans}">Sun, heat, humidity and protective styles had their moment. Now it’s time to come back to softness, moisture and a wash-day ritual made for your healthiest season yet.</p>${button("Build Your Reset Routine", emailUrl("/products/hair-wellness-bundle"), "center")}</td></tr><tr><td class="px" style="padding:40px 30px;background:#f8f1e7"><h2 class="h-md" style="margin:0 0 8px;text-align:center;font:normal 36px ${BRAND.serif}">The four-step comeback</h2><p style="margin:0 0 24px;text-align:center;font:13px/21px ${BRAND.sans};color:#5f554c">A simple rhythm for returning your hair to the care it deserves.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#fff">${steps}</table></td></tr><tr><td style="padding:46px 34px;background:#667143;color:#fff;text-align:center"><p style="margin:0 0 15px;font:italic 30px/1.2 ${BRAND.serif}">“Your next wash day is a chance to begin again.”</p><span style="font:11px ${BRAND.sans};letter-spacing:.16em;text-transform:uppercase">No sale. Just care.</span></td></tr>${footer(email)}`);
}

function freeShipping(email: string) {
  const rows = [["1","CLEANSE","Lathyr creates the fresh foundation."],["2","CONDITION","Choose Uplyft or Revaivl for your current hair goals."],["3","HYDRATE","Replenish moisture and refresh your strands."],["4","NOURISH","Seal in your care and complete the practice."]].map(([n,h,p]) => `<tr><td style="width:42px;padding:16px 0;border-top:1px solid #ddd0c0"><span style="display:inline-block;width:28px;height:28px;border-radius:50%;background:${BRAND.pink};color:#fff;text-align:center;font:bold 12px/28px ${BRAND.sans}">${n}</span></td><td style="padding:16px 0;border-top:1px solid #ddd0c0"><b style="font:12px ${BRAND.sans};letter-spacing:.1em">${h}</b><span style="display:block;margin-top:4px;font:12px/19px ${BRAND.sans};color:#6f6258">${p}</span></td></tr>`).join("");
  return shell("Free shipping for your wash-day ritual, for a limited time.", `<tr><td style="padding:16px;background:${BRAND.pink};color:#fff;text-align:center;font:900 13px ${BRAND.sans};letter-spacing:.14em;text-transform:uppercase">Free shipping · Limited time only</td></tr>${brandRow("The Wash-Day Edit")}<tr><td>${image("/email/wash-day-shelf.jpg", "Wynn Essentials wash-day products on a spa shelf")}</td></tr><tr><td class="px" style="padding:40px 34px;background:#efe0ca;text-align:center"><p style="margin:0;font:800 11px ${BRAND.sans};letter-spacing:.2em;text-transform:uppercase">Take your time</p>${title("Wash day, but make it a ritual.")}<p style="margin:0 auto 24px;max-width:470px;font:15px/25px ${BRAND.sans}">Turn the routine into your reset. Choose the essentials your hair needs and we’ll take care of the shipping.</p>${pinkButton("Shop With Free Shipping", emailUrl("/"))}</td></tr><tr><td class="px" style="padding:42px 34px"><h2 class="h-md" style="margin:0 0 8px;text-align:center;font:normal 36px ${BRAND.serif}">Your ritual, your way</h2><p style="margin:0 0 24px;text-align:center;font:13px/21px ${BRAND.sans};color:#5f554c">Start with the step your shelf is missing—or bring home the full practice.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0">${rows}</table></td></tr><tr><td style="padding:46px 34px;background:#2e231c;color:#fff;text-align:center"><p style="margin:0 0 15px;font:italic 30px/1.2 ${BRAND.serif}">Free shipping. Full permission to pour into yourself.</p><span style="font:11px ${BRAND.sans};letter-spacing:.16em;text-transform:uppercase">For a limited time</span></td></tr>${footer(email)}`);
}

function finalHours(email: string) {
  return shell("Final hours: save 20% with code LABORDAY20 before midnight PT.", `<tr><td style="padding:10px 16px;background:#17130f;color:#fff;text-align:center;font:10px ${BRAND.sans};letter-spacing:.15em;text-transform:uppercase">Final hours · Labor Day offer ends tonight</td></tr>${brandRow("Last Call for the Reset")}<tr><td class="px" style="padding:48px 30px 38px;border-top:5px solid ${BRAND.pink};background:#f3e3cf;text-align:center"><span style="display:inline-block;padding:9px 14px;background:${BRAND.pink};color:#fff;font:900 10px ${BRAND.sans};letter-spacing:.2em;text-transform:uppercase">Labor Day · Final Hours</span>${title("A little something<br>for your next ritual.")}<p style="margin:10px 0 0;color:${BRAND.pink};font:900 100px/.8 ${BRAND.sans};letter-spacing:-.08em">20<span style="font-size:28px;letter-spacing:0">% OFF</span></p></td></tr><tr><td style="padding:0 34px 36px;background:#f3e3cf">${image("/email/labor-day-final-hours.jpg", "Wynn Essentials products styled for healthy-hair routines")}</td></tr><tr><td class="px" style="padding:36px 30px;background:#2e231c;color:#fff;text-align:center"><p style="margin:0 0 10px;font:10px ${BRAND.sans};letter-spacing:.18em;text-transform:uppercase;color:#e9d7c0">Your Labor Day code</p><p style="max-width:290px;margin:0 auto 22px;padding:13px;border:1px dashed ${BRAND.pink};font:900 23px ${BRAND.sans};letter-spacing:.12em">LABORDAY20</p>${pinkButton("Save 20% Now", emailUrl("/"))}</td></tr><tr><td class="px" style="padding:40px 34px;text-align:center"><h2 class="h-md" style="margin:0 0 12px;font:normal 36px ${BRAND.serif}">Before the long weekend ends...</h2><p style="margin:0 auto 24px;max-width:450px;font:14px/23px ${BRAND.sans};color:#5f554c">Restock a favorite, fill the gap in your routine or build your healthy-hair practice from the beginning. Tonight is your final chance to save 20%.</p>${button("Shop the Final Hours", emailUrl("/"), "center")}</td></tr>${footer(email, "<br>Offer ends September 7, 2026 at 11:59 PM PT. Enter LABORDAY20 at checkout.")}`);
}

export function laborDayCampaignEmail(id: LaborDayCampaignId, email: string) {
  const campaign = laborDayCampaigns.find(item => item.id === id)!;
  const html = id === "labor-day-2026-reset" ? reset(email) : id === "labor-day-2026-free-shipping" ? freeShipping(email) : finalHours(email);
  return { subject: campaign.subject, html, text: `${campaign.subject}\n\nShop Wynn Essentials: ${emailUrl("/")}\nUnsubscribe: ${unsubscribeUrl(email)}` };
}
