import { annualMarketingCampaigns } from "./annual-marketing-campaigns";
import { fallCampaigns } from "./fall-campaign-email";
import { laborDayCampaigns } from "./labor-day-campaign-email";

export type InsightFaq = { question: string; answer: string };
export type ScheduledInsight = {
  slug: string;
  title: string;
  excerpt: string;
  body: string;
  coverImage: string;
  author: string;
  status: "published";
  publishedAt: Date;
  createdAt: Date;
  updatedAt: Date;
  keywords: string[];
  faqs: InsightFaq[];
  campaignId: string;
};

type Topic = {
  campaignId: string;
  slug: string;
  title: string;
  keyword: string;
  lens: string;
  context: string;
  steps: [string, string, string, string];
};

const topics: Topic[] = [
  { campaignId: "labor-day-2026-reset", slug: "how-to-reset-your-hair-routine", title: "How to Reset Your Hair Routine Without Starting Over", keyword: "hair routine reset", lens: "A reset is not punishment for what your hair has been through. It is a deliberate pause: notice what changed, remove what is no longer serving you, and rebuild from the scalp outward.", context: "Textured hair responds to seasons, styling tension, product buildup, health, time and consistency. A useful reset separates a temporary symptom from a repeating pattern, then makes the routine simpler enough to repeat.", steps: ["Audit the scalp, strands, ends and current style separately.", "Clarify or cleanse according to buildup—not according to guilt.", "Restore slip and moisture before adding more styling products.", "Choose one small practice to repeat for the next four wash days."] },
  { campaignId: "labor-day-2026-free-shipping", slug: "wash-day-as-ritual-black-hair-history", title: "Wash Day as Ritual: The History, Memory and Care Behind the Practice", keyword: "Black hair wash day ritual", lens: "Wash day is practical, but it has never been only practical. Across generations, hair care has created time for teaching, storytelling, touch, creativity and belonging.", context: "The tools and products have changed, yet the rhythm remains familiar: gather what is needed, work in sections, cleanse, condition, detangle and prepare for the next style. Calling that rhythm a ritual honors both the labor and the meaning carried through it.", steps: ["Prepare the space and products before wetting the hair.", "Cleanse the scalp with patient, intentional movement.", "Condition and detangle in sections, beginning at the ends.", "Close with a style and moisture plan that supports the week ahead."] },
  { campaignId: "fall-reset-2026", slug: "fall-hair-routine-reset", title: "The Fall Hair Reset: How to Adjust Your Routine for a New Season", keyword: "fall hair care routine", lens: "Seasonal change is a useful checkpoint. Cooler air, indoor heat, new schedules and protective styling can change what the hair and scalp need even when the products stay the same.", context: "The goal is not to replace an entire shelf. It is to observe dryness, cleansing frequency, manipulation and moisture retention, then adjust the order or frequency of the practice.", steps: ["Check whether the scalp needs a cleaner start or a gentler cadence.", "Increase conditioning where detangling friction has increased.", "Layer water-based moisture before sealing the ends.", "Plan low-tension styles that make consistency easier."] },
  { campaignId: "national-hair-day-2026", slug: "hair-identity-story-and-care", title: "Hair Tells a Story: Identity, Expression and the Practice of Care", keyword: "Black hair identity and culture", lens: "Hair can hold memory, identity, resistance, play, professionalism, celebration and change. Caring for it well begins by listening to the story it is already telling.", context: "Black hairstyles have long served functional and social roles. They can communicate belonging, status, creativity and life events while protecting textured strands. That history makes hair care both personal and cultural.", steps: ["Name what you want your hair to express—not only how you want it to look.", "Choose styles that respect your scalp and current strand condition.", "Document what works so your routine becomes knowledge.", "Release standards that ask your texture to become something else."] },
  { campaignId: "thanks-2026", slug: "gratitude-and-the-healthy-hair-practice", title: "What Gratitude Has to Do With a Healthy Hair Practice", keyword: "healthy hair practice", lens: "Gratitude changes care from a correction project into a relationship. It makes room to appreciate what the hair does now while still supporting what it needs next.", context: "A practice built on criticism is difficult to sustain. A practice built on attention is more useful: notice resilience, celebrate progress, and make decisions from evidence rather than comparison.", steps: ["Record one sign of progress after every wash day.", "Thank your current texture by choosing compatible techniques.", "Share useful knowledge with someone in your community.", "Treat consistency—not perfection—as the measure of success."] },
  { campaignId: "early-2026", slug: "intentional-haircare-shopping-guide", title: "How to Shop for Hair Care With Intention", keyword: "how to choose hair products", lens: "A full cart is not the same as a complete routine. Intentional shopping begins with a clear need, a place for each product, and a plan for how it will be used.", context: "Product overload often makes it harder to identify what works. A routine becomes more readable when every purchase supports a defined step: cleanse, condition, moisturize, treat, seal or style.", steps: ["Name the problem in observable terms such as flakes, tangles or moisture loss.", "Check what role the new product plays in the routine.", "Compare ingredients and directions with products already open.", "Buy for the next consistent practice, not an imagined future shelf."] },
  { campaignId: "blackfriday-2026", slug: "build-a-complete-healthy-hair-routine", title: "How to Build a Complete Healthy-Hair Routine From Cleanse to Finish", keyword: "complete healthy hair routine", lens: "Healthy hair is not created by one hero product. It is supported by a sequence in which each step prepares the hair for the next.", context: "The most effective routine is not necessarily the longest. It is the one that cleans the scalp, restores manageability, adds moisture where needed and supports styling without unnecessary friction.", steps: ["Cleanse the scalp and allow the lather to travel through the lengths.", "Condition for slip, softness and easier detangling.", "Add water-based moisture while the hair is receptive.", "Seal or style according to porosity, density and the week ahead."] },
  { campaignId: "small-2026", slug: "why-shopping-black-owned-haircare-matters", title: "Why Supporting Black-Owned Hair Care Builds More Than a Routine", keyword: "Black-owned hair care", lens: "When textured-hair knowledge is treated as expertise, communities receive products, language and education shaped by lived experience rather than added as an afterthought.", context: "Supporting a small Black-owned beauty business helps sustain formulation, storytelling, employment, customer education and a more accurate understanding of textured-hair needs.", steps: ["Learn the founder story and the problem the brand set out to solve.", "Buy according to need so support becomes a lasting relationship.", "Leave specific reviews that help another shopper decide.", "Share educational content as well as promotional offers."] },
  { campaignId: "guide-2026", slug: "how-to-gift-haircare-thoughtfully", title: "How to Give Hair Care as a Thoughtful Gift", keyword: "hair care gift guide", lens: "Hair care can be intimate. The best gift respects the recipient’s routine, texture, preferences and boundaries instead of making assumptions about what should be fixed.", context: "A thoughtful hair gift offers support: an easier wash day, a softer bonnet, a replenished staple or time set aside for care. It should feel observant, not corrective.", steps: ["Ask about favorite products, scents and routines when possible.", "Choose a complete use case rather than unrelated products.", "Avoid making medical or growth promises through the gift.", "Include directions or a simple ritual card so the gift feels usable."] },
  { campaignId: "gifting-2026", slug: "the-art-of-building-a-haircare-ritual-gift", title: "The Art of Gifting a Complete Hair-Care Ritual", keyword: "hair care ritual gift", lens: "A curated bundle is strongest when its products work in sequence. The gift becomes an experience: prepare, cleanse, condition, moisturize and protect.", context: "Ritual gifting communicates care because it considers what happens before and after the beautiful moment of opening the box.", steps: ["Start with the recipient’s most repeated hair-care moment.", "Pair products whose directions naturally work together.", "Add one comfort item that protects the result overnight.", "Explain the order of use in a short, welcoming note."] },
  { campaignId: "lastminute-2026", slug: "self-care-hair-ritual-during-busy-seasons", title: "A Hair Ritual for You: Protecting Self-Care During Busy Seasons", keyword: "hair self care ritual", lens: "Self-care does not have to be elaborate to be meaningful. During a crowded season, a shorter practice done with attention can be more restorative than a perfect routine postponed indefinitely.", context: "Hair care can create a physical pause: warm water, sectioning, scalp touch and deliberate breathing. The value is not indulgence alone; it is returning to the body and noticing what needs care.", steps: ["Choose the one hair task that will create the most relief.", "Reduce setup by keeping a small ritual basket ready.", "Protect ten uninterrupted minutes instead of waiting for hours.", "Finish in a low-manipulation style that gives time back."] },
  { campaignId: "reset-2026", slug: "post-holiday-hair-reset", title: "The Post-Holiday Hair Reset: Moisture, Scalp Care and Less Manipulation", keyword: "post holiday hair reset", lens: "After heat, travel, celebration styles and changed schedules, the hair may need recovery rather than another demanding look.", context: "A post-holiday reset focuses on removing buildup, restoring slip, checking the ends and choosing a low-tension next style. It is a return to baseline, not an emergency overhaul.", steps: ["Take down the style slowly and detangle before cleansing when appropriate.", "Clean the scalp thoroughly without piling the lengths.", "Use conditioning time to assess elasticity and breakage.", "Choose a simple style that limits tension and daily handling."] },
  { campaignId: "newyear-2026", slug: "healthy-hair-habits-that-last", title: "New Year, Sustainable Practice: Hair Habits That Actually Last", keyword: "healthy hair habits", lens: "A resolution depends on motivation. A practice depends on cues, tools and repetition. Hair goals become more durable when they are translated into small behaviors.", context: "Instead of promising length or perfection, define actions you can control: cleanse on a realistic cadence, protect hair at night, moisturize based on observation and review results monthly.", steps: ["Choose one measurable habit for the first month.", "Attach it to a cue that already exists in your week.", "Make the products and tools visible and easy to reach.", "Review results after four repetitions before changing course."] },
  { campaignId: "winter-2027", slug: "winter-moisture-routine-for-textured-hair", title: "A Winter Moisture Routine for Textured Hair", keyword: "winter moisture routine for textured hair", lens: "Winter dryness is not solved by adding oil to dry hair. Moisture begins with water and conditioning, then lasts longer when the routine reduces exposure and friction.", context: "Cold outdoor air and heated indoor spaces can increase the feeling of dryness. Textured hair often benefits from thoughtful layering, protected ends and fewer unnecessary resets.", steps: ["Cleanse often enough for the scalp while avoiding rough handling.", "Condition thoroughly and detangle while slip is present.", "Apply a water-based moisturizer in sections.", "Seal the ends and protect them from fabrics and weather."] },
  { campaignId: "mlk-2027", slug: "care-service-and-building-what-our-community-needs", title: "Care as Service: Building What Our Community Needs", keyword: "Black beauty community care", lens: "A healthy-hair practice can be personal and still be part of a larger act of service. Knowledge becomes more powerful when it is shared in language people can use.", context: "Community-centered beauty work listens before it sells. It identifies overlooked needs, respects cultural practice and creates tools that help people care for themselves with dignity.", steps: ["Listen for the question underneath the product request.", "Share clear education without shame or gatekeeping.", "Design routines for real schedules and real budgets.", "Measure success by usefulness as well as visibility."] },
  { campaignId: "history-2027", slug: "black-hair-history-rooted-in-care", title: "Rooted in Care: What Black Hair History Teaches Us", keyword: "Black hair history", lens: "Black hair history is a record of artistry, survival, identity, labor, resistance and joy. Its meaning cannot be reduced to a trend cycle.", context: "Styles such as cornrows and Bantu knots have deep cultural histories and have served functional and social roles. In the United States, Black hair has also been regulated, stereotyped and reclaimed, making everyday care part of a broader story.", steps: ["Learn the names and origins of styles before borrowing their language.", "Honor the skill and labor of braiders and stylists.", "Teach younger generations the story alongside the technique.", "Choose care practices that protect both the hair and its cultural meaning."] },
  { campaignId: "love-2027", slug: "learning-your-hairs-love-language", title: "Learning Your Hair’s Love Language", keyword: "how to understand your hair needs", lens: "Hair does not communicate in product names. It communicates through tangling, softness, buildup, breakage, shrinkage, scalp comfort and how long a style remains manageable.", context: "Learning that language means replacing assumptions with observation. The same texture can need a different response after weather changes, a new style or a period of stress.", steps: ["Notice how the hair feels before adding product.", "Change one variable at a time so the result is readable.", "Use softness, manageability and scalp comfort as practical signals.", "Keep a brief wash-day note instead of relying on memory."] },
  { campaignId: "valentine-2027", slug: "love-your-hair-through-consistent-care", title: "Love Your Hair Through Consistent Care, Not Perfection", keyword: "loving your natural hair", lens: "Hair love is not a requirement to enjoy every wash day. It is the decision to care without using comparison, shame or impossible standards as motivation.", context: "Consistency creates trust. When the routine becomes predictable, it is easier to recognize changes, respond early and celebrate the texture as it is.", steps: ["Replace appearance-only goals with care-based goals.", "Choose language that describes rather than judges.", "Make room for ease, adornment and experimentation.", "Return to the practice after disruption without calling it failure."] },
  { campaignId: "spotlight-2027", slug: "the-impact-of-black-owned-beauty", title: "The Wider Impact of Black-Owned Beauty", keyword: "support Black-owned beauty brands", lens: "Black-owned beauty expands who gets to define expertise, whose needs shape innovation and which stories are visible on the shelf.", context: "The impact reaches beyond a transaction. It can support jobs, supplier relationships, culturally competent education, community reinvestment and products developed with textured hair at the center.", steps: ["Seek brands whose education matches their claims.", "Become a repeat customer when a product earns a place in the routine.", "Give useful feedback and document real results.", "Recommend with specificity so trust travels with the referral."] },
  { campaignId: "women-2027", slug: "women-who-built-the-practice-of-hair-care", title: "The Women Who Built the Practice of Hair Care", keyword: "Black women hair care history", lens: "Hair-care knowledge has often moved through women’s hands: in kitchens, salons, laboratories, family businesses and community spaces.", context: "That labor includes formulation, styling, teaching, entrepreneurship and the emotional work of helping someone feel seen. Women’s history in beauty is therefore both commercial history and care history.", steps: ["Learn the founder behind the formula or technique.", "Credit the person and culture that developed the knowledge.", "Pay fairly for skilled styling and consultation.", "Preserve family routines by recording the why, not only the steps."] },
  { campaignId: "iwd-2027", slug: "care-work-women-and-beauty-rituals", title: "Care Work, Beauty Rituals and the Women Who Make Them Possible", keyword: "women beauty care work", lens: "A polished result can hide hours of invisible work. Wash day, braiding, formulation, packaging and customer care all rely on attention that deserves recognition.", context: "Naming care as work does not remove its love. It makes the skill, time and expertise visible—and invites more equitable ways to value the people who provide it.", steps: ["Ask how much time a routine truly requires.", "Share responsibilities at home when hair care involves children.", "Respect professional boundaries and appointment policies.", "Celebrate the expertise behind the finished style."] },
  { campaignId: "spring-2027", slug: "spring-scalp-and-hair-reset", title: "The Spring Reset: A Cleaner Scalp and a Lighter Routine", keyword: "spring hair care reset", lens: "Spring is an invitation to remove excess—not moisture, but buildup, clutter and steps that no longer have a purpose.", context: "A lighter routine can improve consistency. The goal is to clean the scalp, identify what is actually being used and make room for weather, movement and new styling plans.", steps: ["Review open products and retire duplicates or expired items.", "Clean tools, bonnets, scarves and storage surfaces.", "Clarify when buildup signals the need, then condition well.", "Keep the few steps that produce repeatable results."] },
  { campaignId: "easter-2027", slug: "spring-hair-accessories-and-intentional-styling", title: "Spring Styling: Adornment, Accessories and Intentional Hair Play", keyword: "spring hairstyles textured hair", lens: "Adornment can change a style without asking the hair to endure more heat or tension. Scarves, scrunchies, pins and shape make room for play while preserving the practice.", context: "The most useful styling plan begins with the condition of the hair, then chooses an accessory that supports—not fights—the foundation.", steps: ["Moisturize and detangle before decorating the style.", "Choose soft, smooth accessories at points of contact.", "Avoid repeating tight placement in the same area.", "Remove accessories gently and store them clean."] },
  { campaignId: "prep-2027", slug: "protective-style-prep-checklist", title: "The Protective-Style Prep Checklist Your Hair Deserves", keyword: "protective style preparation", lens: "A protective style protects only when the foundation, installation and maintenance reduce stress on the hair and scalp.", context: "Preparation is where the long-term result begins. Clean hair, thorough conditioning, gentle detangling and an honest tension conversation matter more than how long the style lasts.", steps: ["Cleanse and condition before installation.", "Detangle fully without rushing through resistant sections.", "Discuss weight, braid size and hairline tension with the stylist.", "Plan scalp access, nighttime protection and a removal date."] },
  { campaignId: "earth-2027", slug: "intentional-ingredient-literacy-for-haircare", title: "Ingredient Literacy: How to Read Hair-Care Claims With Intention", keyword: "how to read hair product ingredients", lens: "An ingredient list is useful, but it is not a verdict by itself. Formula, concentration, product type, directions and your own response all matter.", context: "Ingredient literacy helps shoppers move beyond fear-based lists and miracle claims. It asks a better question: what is this formula designed to do, and where does it fit in the practice?", steps: ["Read the product purpose and directions before isolating one ingredient.", "Separate evidence for hair feel from evidence for hair growth.", "Patch test when sensitivity or a reactive scalp is a concern.", "Track the result across several consistent uses."] },
  { campaignId: "mom-2027", slug: "thoughtful-haircare-gifts-for-mothers", title: "Thoughtful Hair-Care Gifts for Mothers and Caregivers", keyword: "hair care gifts for mom", lens: "The most meaningful care gift recognizes the person beyond the role she fills for everyone else.", context: "A good hair-care gift can return time, comfort or ease. The key is to choose around her actual routine rather than assigning her a new project.", steps: ["Notice which staple she replaces most often.", "Choose ease: a complete set, a soft accessory or a treatment moment.", "Include time or help so she can use the gift.", "Keep the message appreciative rather than corrective."] },
  { campaignId: "last-2027", slug: "mother-daughter-hair-care-knowledge", title: "What Hair Care Passes From One Generation to the Next", keyword: "mother daughter Black hair care", lens: "Hair knowledge is often inherited through gestures: how to part, how to hold the ends, when to add water and how to make a child feel safe in the chair.", context: "Not every inherited practice must stay unchanged. The gift is the ability to preserve tenderness and cultural memory while updating techniques with better information.", steps: ["Ask elders why a technique became part of the routine.", "Keep the practices that protect comfort and connection.", "Change methods that rely on pain, shame or excessive tension.", "Record recipes, stories and styling knowledge for the next generation."] },
  { campaignId: "grad-2027", slug: "healthy-hair-routine-for-life-transitions", title: "A Healthy-Hair Routine for Life’s Next Chapter", keyword: "simple healthy hair routine", lens: "A new job, school, city or schedule changes the time and tools available for hair care. The routine should evolve before it collapses under old expectations.", context: "Transition-friendly care is portable, predictable and forgiving. It protects the essentials while leaving room for the person you are becoming.", steps: ["Identify the three steps that make the biggest difference.", "Create a shorter weekday version and a fuller reset version.", "Choose styles compatible with the new calendar.", "Pack a small kit before the transition begins."] },
  { campaignId: "memorial-2027", slug: "summer-hair-moisture-and-protection", title: "Summer Hair Starts With Moisture, Protection and a Plan", keyword: "summer hair care for textured hair", lens: "Summer brings sun, sweat, water and travel. A seasonal routine works best when it anticipates exposure instead of trying to repair everything afterward.", context: "The scalp may need a different cleansing cadence while the lengths need help holding moisture and avoiding friction. The answer is often better timing, not simply more product.", steps: ["Rinse or cleanse after heavy sweat, chlorine or salt exposure.", "Condition and detangle before dryness becomes matting.", "Use a water-based moisturizer, then protect the ends.", "Carry a scarf or bonnet so travel does not erase the practice."] },
  { campaignId: "juneteenth-2027", slug: "juneteenth-black-hair-freedom-and-legacy", title: "Juneteenth, Black Hair Freedom and the Legacy We Carry", keyword: "Juneteenth Black hair history", lens: "Freedom includes the right to define beauty, wear cultural styles and pass knowledge forward without asking dominant standards for permission.", context: "Black hair has been controlled through law, policy and social pressure, yet it has remained a site of invention and pride. Juneteenth offers space to honor that endurance while recognizing that hair freedom still requires protection.", steps: ["Learn the local history behind Black hair and beauty businesses.", "Support policies that challenge race-based hair discrimination.", "Celebrate styles with context and proper credit.", "Pass forward a practice rooted in choice rather than conformity."] },
  { campaignId: "dad-2027", slug: "simple-hair-and-scalp-routine-for-men", title: "A Simple Hair and Scalp Routine for Men Who Keep Showing Up", keyword: "hair and scalp routine for Black men", lens: "A useful routine for men does not need ten steps. It needs regular cleansing, attention to the scalp, moisture where needed and grooming that does not create chronic irritation.", context: "Short hair, waves, locs, braids and beards each change the details, but the foundation remains observation and consistency.", steps: ["Cleanse based on sweat, buildup and scalp comfort.", "Condition textured lengths even when the style is short.", "Use oils sparingly as a seal or scalp comfort step—not a substitute for cleansing.", "Address persistent itching, pain or hair loss with a dermatologist."] },
  { campaignId: "freedom-2027", slug: "freedom-to-wear-your-hair-your-way", title: "The Freedom to Wear Your Hair Your Way", keyword: "natural hair freedom", lens: "Hair freedom means choice: natural, braided, loc’d, straightened, covered, extended, cut or colored—without one expression being treated as more worthy than another.", context: "Choice becomes real when people have accurate care information, protection from discrimination and the resources to maintain the style they select.", steps: ["Choose from preference rather than pressure.", "Understand the maintenance and risk profile of the style.", "Protect the scalp and hairline during installation and wear.", "Respect another person’s choice without ranking textures or styles."] },
  { campaignId: "hydrate-2027", slug: "mid-summer-moisture-check", title: "The Mid-Summer Moisture Check: Is Your Hair Asking for Water?", keyword: "dry textured hair in summer", lens: "Hair can feel coated and still be under-moisturized. A mid-season check distinguishes lack of water from buildup, damage or a product combination that is no longer working.", context: "Useful clues include how quickly the hair wets, how it behaves during detangling, whether softness lasts and whether the scalp feels clean.", steps: ["Clarify the difference between dry hair and product-coated hair.", "Reintroduce moisture on clean, receptive strands.", "Work in sections so the middle and ends are not skipped.", "Adjust sealing weight to the weather and the style."] },
  { campaignId: "blackbiz-2027", slug: "black-business-month-beauty-and-community", title: "Black Business Month: Beauty, Ownership and Community", keyword: "Black-owned beauty business impact", lens: "Ownership changes who makes decisions, whose needs are centered and where value can circulate.", context: "A Black-owned hair-care company can translate lived experience into products and education while building an institution that outlasts a single campaign.", steps: ["Look beyond the label and learn how the business serves customers.", "Support consistently, not only during commemorative months.", "Share detailed testimonials that strengthen trust.", "Invite the brand into conversations, partnerships and opportunities."] },
  { campaignId: "school-2027", slug: "back-to-school-hair-routine", title: "A Back-to-School Hair Routine That Makes Mornings Easier", keyword: "back to school hair routine", lens: "A school routine should protect confidence, comfort and time. The best style is one the child can wear without pain and the household can maintain without daily conflict.", context: "Preparation on wash day reduces morning manipulation. Involving children in age-appropriate choices also teaches body autonomy and hair knowledge.", steps: ["Choose a realistic style based on schedule and activity.", "Cleanse, condition and detangle without rushing.", "Keep hairline tension low and ask about discomfort.", "Prepare a small refresh kit and a clear nighttime routine."] },
  { campaignId: "protect-2027", slug: "protective-style-season-starts-underneath", title: "Protective-Style Season Starts Underneath the Style", keyword: "protective style hair care", lens: "What is hidden still needs care. A style cannot protect hair that was installed under excessive tension, left with buildup or ignored until removal.", context: "The health of a protective style is determined by preparation, weight, access to the scalp, moisture strategy, wear time and patient removal.", steps: ["Begin with clean, conditioned and fully detangled hair.", "Choose length and density that your roots can comfortably carry.", "Monitor the hairline and remove the style if pain persists.", "Schedule removal before matting and buildup make it difficult."] },
  { campaignId: "reset-2027", slug: "end-of-summer-hair-reset", title: "The End-of-Summer Hair Reset", keyword: "end of summer hair care", lens: "The end of summer is a useful time to assess what sun, sweat, swimming, travel and protective styling changed.", context: "A reset creates a clean record before fall: scalp comfort, strand condition, ends, breakage patterns and which parts of the routine remained realistic.", steps: ["Remove long-worn styles gently and completely.", "Cleanse the scalp and lengths according to buildup.", "Condition, detangle and assess the ends in sections.", "Set one fall goal based on what the summer actually taught you."] },
];

const excludedCampaignIds = new Set(["labor-day-2026-final-hours", "cyber-2026", "final-2026", "shipping-2026"]);
const allCampaigns = [...laborDayCampaigns, ...fallCampaigns, ...annualMarketingCampaigns];
const campaigns = new Map<string, (typeof allCampaigns)[number]>(
  allCampaigns.map(campaign => [campaign.id, campaign]),
);

const campaignImages: Record<string, string> = {
  "labor-day-2026-reset": "/email/labor-day-reset.jpg",
  "labor-day-2026-free-shipping": "/email/wash-day-shelf.jpg",
  "fall-reset-2026": "/newsletter/newsletter-wellness-lineup.webp",
  "national-hair-day-2026": "/collections/wynn-essentials-natural-girlies.webp",
};

const sources = {
  history: "- [Strands of Inspiration: Exploring Black Identities through Hair — Smithsonian NMAAHC](https://nmaahc.si.edu/explore/stories/strands-of-inspiration)\n- [Heavy Is the Hair: Evolution of African Hair in America — Library of Congress](https://blogs.loc.gov/ofthepeople/2023/11/ccdi-junior-fellow-spotlight-majestie-varnado-heavy-is-the-hair/)",
  care: "- [Hair-care tips from dermatologists — American Academy of Dermatology](https://www.aad.org/news/tressed-to-impress-hair-tips)\n- [Hairstyles that pull can lead to hair loss — American Academy of Dermatology](https://www.aad.org/public/diseases/hair-loss/causes/hairstyles)",
};

function makeFaqs(topic: Topic): InsightFaq[] {
  return [
    { question: `What is the most important part of ${topic.keyword}?`, answer: `The most important part is consistency guided by observation. Start with the scalp and current condition of the hair, then choose the smallest useful action you can repeat.` },
    { question: "How quickly should I change my routine?", answer: "Change one variable at a time when possible. Unless there is pain, irritation or significant breakage, give a well-chosen practice several uses so you can evaluate the pattern rather than one day." },
    { question: "When should I ask a professional for help?", answer: "Persistent itching, burning, sores, sudden shedding, bald patches or ongoing pain deserve attention from a board-certified dermatologist. A stylist can support technique, but a medical concern needs medical care." },
  ];
}

function makeBody(topic: Topic, faqs: InsightFaq[]) {
  const historyFocused = /history|ritual|identity|legacy|freedom|women|community|Black-owned|Black business|Juneteenth/i.test(`${topic.title} ${topic.keyword}`);
  return `${topic.lens}

## The deeper meaning

${topic.context}

At Wynn Essentials, **Healthy Hair Is a Practice** means care is not a single product, a perfect style or a promise of overnight change. It is a repeatable relationship between knowledge, observation and action. The routine should make the hair easier to understand—not make the person feel as though her texture is a problem to solve.

## What to pay attention to

Start with evidence you can see and feel: scalp comfort, buildup, tangling, breakage, elasticity, softness, shedding, the condition of the ends and how much tension a style creates. Products matter, but technique, frequency and the order of use often determine whether a product gets the chance to work as intended.

Textured hair is not one uniform category. Density, strand diameter, curl pattern, porosity, styling history and scalp condition can all change the best approach. Use general guidance as a starting point, then personalize it through careful observation.

## Put it into practice

1. **${topic.steps[0]}**
2. **${topic.steps[1]}**
3. **${topic.steps[2]}**
4. **${topic.steps[3]}**

The goal is not to complete every possible step. It is to understand why each chosen step is present and what result it should support. When something stops working, return to the evidence before buying more or adding complexity.

## How to evaluate the result

Evaluate a routine by more than the first-day finish. Notice what happens during detangling, how the scalp feels between wash days, whether the ends remain pliable, how much hair is breaking during manipulation and how easily the next wash day begins. Those observations reveal whether the practice is supporting the hair—not merely coating it.

Keep the evaluation simple. Write down the date, the style, the products used and one or two observations. After several repetitions, look for a pattern. A single humid day, rushed wash or unfamiliar style can distort the result; a pattern gives you better information.

If the routine causes burning, persistent itching, sores, pain or sudden hair loss, stop treating the issue as a cosmetic adjustment. Those signs warrant professional evaluation. Healthy-hair education should help a person recognize the limit of home care, not encourage her to push through symptoms.

## A Wynn Essentials reflection

Ask yourself: *What is my hair requesting from me right now—and what part of that request can I meet consistently?* That question keeps the practice responsive. It also leaves room for beauty, culture, creativity and ease to exist alongside hair health.

## Frequently asked questions

${faqs.map(faq => `### ${faq.question}\n\n${faq.answer}`).join("\n\n")}

## Sources and further reading

${historyFocused ? `${sources.history}\n` : ""}${sources.care}

*This article is educational and is not medical advice. If you have persistent scalp symptoms or sudden hair loss, consult a board-certified dermatologist.*`;
}

export const scheduledInsights: ScheduledInsight[] = topics.map(topic => {
  const campaign = campaigns.get(topic.campaignId);
  if (!campaign) throw new Error(`Missing email campaign for insight: ${topic.campaignId}`);
  if (excludedCampaignIds.has(topic.campaignId)) throw new Error(`Excluded campaign has an insight: ${topic.campaignId}`);
  const faqs = makeFaqs(topic);
  const image = "image" in campaign && typeof campaign.image === "string" ? campaign.image : campaignImages[topic.campaignId];
  return {
    slug: topic.slug,
    title: topic.title,
    excerpt: `${topic.lens} A deeper Wynn Essentials guide to ${topic.keyword}.`,
    body: makeBody(topic, faqs),
    coverImage: image || "/og-basket-espresso.jpg",
    author: "Wynn Essentials",
    status: "published",
    publishedAt: campaign.scheduledAt,
    createdAt: campaign.scheduledAt,
    updatedAt: campaign.scheduledAt,
    keywords: [topic.keyword, "textured hair care", "healthy hair practice", "Wynn Essentials"],
    faqs,
    campaignId: topic.campaignId,
  };
});

export const liveScheduledInsights = (now = new Date()) => scheduledInsights.filter(insight => insight.publishedAt <= now);
export const scheduledInsightBySlug = (slug: string, now = new Date()) => liveScheduledInsights(now).find(insight => insight.slug === slug) ?? null;

if (scheduledInsights.length !== allCampaigns.length - excludedCampaignIds.size) {
  throw new Error(`Expected ${allCampaigns.length - excludedCampaignIds.size} campaign insights, found ${scheduledInsights.length}`);
}
